/*
 * Criteo API
 * Criteo API - MarketingSolutions
 *
 * The version of the OpenAPI document: 2026-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.marketingsolutions.v2026_01.model;

import java.util.Objects;
import java.util.Arrays;
import com.criteo.api.marketingsolutions.v2026_01.model.AdaptiveColors;
import com.criteo.api.marketingsolutions.v2026_01.model.ImageSet;
import com.criteo.api.marketingsolutions.v2026_01.model.ImageShape;
import com.criteo.api.marketingsolutions.v2026_01.model.VideoDetail;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.criteo.api.marketingsolutions.v2026_01.JSON;

/**
 * The attributes specific to Adaptive creatives
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AdaptiveAttributes {
  public static final String SERIALIZED_NAME_CALLS_TO_ACTION = "callsToAction";
  @SerializedName(SERIALIZED_NAME_CALLS_TO_ACTION)
  private List<String> callsToAction = new ArrayList<>();

  public static final String SERIALIZED_NAME_COLORS = "colors";
  @SerializedName(SERIALIZED_NAME_COLORS)
  private AdaptiveColors colors;

  public static final String SERIALIZED_NAME_DESCRIPTION_FONT = "descriptionFont";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION_FONT)
  private String descriptionFont;

  public static final String SERIALIZED_NAME_DESCRIPTION_TEXT = "descriptionText";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION_TEXT)
  private String descriptionText;

  public static final String SERIALIZED_NAME_HEADLINE_FONT = "headlineFont";
  @SerializedName(SERIALIZED_NAME_HEADLINE_FONT)
  private String headlineFont;

  public static final String SERIALIZED_NAME_HEADLINE_TEXT = "headlineText";
  @SerializedName(SERIALIZED_NAME_HEADLINE_TEXT)
  private String headlineText;

  /**
   * Value can be \&quot;ShowFullImage\&quot; or \&quot;ZoomOnImage\&quot;. Choose whether your image set should fit inside the allocated  space (\&quot;ShowFullImage\&quot;) or whether it should fill that space (\&quot;ZoomOnImage\&quot;). If you choose ZoomOnImage, there may be some  image cropping.
   */
  @JsonAdapter(ImageDisplayEnum.Adapter.class)
  public enum ImageDisplayEnum {
    SHOWFULLIMAGE("ShowFullImage"),
    
    ZOOMONIMAGE("ZoomOnImage");

    private String value;

    ImageDisplayEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ImageDisplayEnum fromValue(String value) {
      for (ImageDisplayEnum b : ImageDisplayEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ImageDisplayEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ImageDisplayEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ImageDisplayEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ImageDisplayEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_IMAGE_DISPLAY = "imageDisplay";
  @SerializedName(SERIALIZED_NAME_IMAGE_DISPLAY)
  private ImageDisplayEnum imageDisplay;

  public static final String SERIALIZED_NAME_IMAGE_SETS = "imageSets";
  @SerializedName(SERIALIZED_NAME_IMAGE_SETS)
  private List<ImageSet> imageSets = null;

  public static final String SERIALIZED_NAME_LANDING_PAGE_URL = "landingPageUrl";
  @SerializedName(SERIALIZED_NAME_LANDING_PAGE_URL)
  private URI landingPageUrl;

  /**
   * Gets or Sets layouts
   */
  @JsonAdapter(LayoutsEnum.Adapter.class)
  public enum LayoutsEnum {
    EDITORIAL("Editorial"),
    
    MONTAGE("Montage"),
    
    INBANNERVIDEO("InBannerVideo");

    private String value;

    LayoutsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LayoutsEnum fromValue(String value) {
      for (LayoutsEnum b : LayoutsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LayoutsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LayoutsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LayoutsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LayoutsEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_LAYOUTS = "layouts";
  @SerializedName(SERIALIZED_NAME_LAYOUTS)
  private List<LayoutsEnum> layouts = new ArrayList<>();

  public static final String SERIALIZED_NAME_LOGOS = "logos";
  @SerializedName(SERIALIZED_NAME_LOGOS)
  private List<ImageShape> logos = new ArrayList<>();

  public static final String SERIALIZED_NAME_VIDEOS = "videos";
  @SerializedName(SERIALIZED_NAME_VIDEOS)
  private List<VideoDetail> videos = null;

  public AdaptiveAttributes() {
  }

  public AdaptiveAttributes callsToAction(List<String> callsToAction) {
    
    this.callsToAction = callsToAction;
    return this;
  }

  public AdaptiveAttributes addCallsToActionItem(String callsToActionItem) {
    this.callsToAction.add(callsToActionItem);
    return this;
  }

   /**
   * A Call-to-Action (CTA) is an action-driven instruction to your audience intended to provoke an immediate  response, such as “Buy now” or “Go!”.
   * @return callsToAction
  **/
  @javax.annotation.Nonnull

  public List<String> getCallsToAction() {
    return callsToAction;
  }


  public void setCallsToAction(List<String> callsToAction) {
    this.callsToAction = callsToAction;
  }


  public AdaptiveAttributes colors(AdaptiveColors colors) {
    
    this.colors = colors;
    return this;
  }

   /**
   * Get colors
   * @return colors
  **/
  @javax.annotation.Nullable

  public AdaptiveColors getColors() {
    return colors;
  }


  public void setColors(AdaptiveColors colors) {
    this.colors = colors;
  }


  public AdaptiveAttributes descriptionFont(String descriptionFont) {
    
    this.descriptionFont = descriptionFont;
    return this;
  }

   /**
   * Font of the description  Valid supported font like \&quot;Arial\&quot;
   * @return descriptionFont
  **/
  @javax.annotation.Nonnull

  public String getDescriptionFont() {
    return descriptionFont;
  }


  public void setDescriptionFont(String descriptionFont) {
    this.descriptionFont = descriptionFont;
  }


  public AdaptiveAttributes descriptionText(String descriptionText) {
    
    this.descriptionText = descriptionText;
    return this;
  }

   /**
   * The description text of the banner
   * @return descriptionText
  **/
  @javax.annotation.Nonnull

  public String getDescriptionText() {
    return descriptionText;
  }


  public void setDescriptionText(String descriptionText) {
    this.descriptionText = descriptionText;
  }


  public AdaptiveAttributes headlineFont(String headlineFont) {
    
    this.headlineFont = headlineFont;
    return this;
  }

   /**
   * Font of the headline  Valid supported font like \&quot;Arial\&quot;
   * @return headlineFont
  **/
  @javax.annotation.Nonnull

  public String getHeadlineFont() {
    return headlineFont;
  }


  public void setHeadlineFont(String headlineFont) {
    this.headlineFont = headlineFont;
  }


  public AdaptiveAttributes headlineText(String headlineText) {
    
    this.headlineText = headlineText;
    return this;
  }

   /**
   * The headline text of the banner
   * @return headlineText
  **/
  @javax.annotation.Nonnull

  public String getHeadlineText() {
    return headlineText;
  }


  public void setHeadlineText(String headlineText) {
    this.headlineText = headlineText;
  }


  public AdaptiveAttributes imageDisplay(ImageDisplayEnum imageDisplay) {
    
    this.imageDisplay = imageDisplay;
    return this;
  }

   /**
   * Value can be \&quot;ShowFullImage\&quot; or \&quot;ZoomOnImage\&quot;. Choose whether your image set should fit inside the allocated  space (\&quot;ShowFullImage\&quot;) or whether it should fill that space (\&quot;ZoomOnImage\&quot;). If you choose ZoomOnImage, there may be some  image cropping.
   * @return imageDisplay
  **/
  @javax.annotation.Nullable

  public ImageDisplayEnum getImageDisplay() {
    return imageDisplay;
  }


  public void setImageDisplay(ImageDisplayEnum imageDisplay) {
    this.imageDisplay = imageDisplay;
  }


  public AdaptiveAttributes imageSets(List<ImageSet> imageSets) {
    
    this.imageSets = imageSets;
    return this;
  }

  public AdaptiveAttributes addImageSetsItem(ImageSet imageSetsItem) {
    if (this.imageSets == null) {
      this.imageSets = null;
    }
    this.imageSets.add(imageSetsItem);
    return this;
  }

   /**
   * Multiple image sets, each image set consists of multiple images and a headline text.
   * @return imageSets
  **/
  @javax.annotation.Nullable

  public List<ImageSet> getImageSets() {
    return imageSets;
  }


  public void setImageSets(List<ImageSet> imageSets) {
    this.imageSets = imageSets;
  }


  public AdaptiveAttributes landingPageUrl(URI landingPageUrl) {
    
    this.landingPageUrl = landingPageUrl;
    return this;
  }

   /**
   * Web redirection of the landing page url
   * @return landingPageUrl
  **/
  @javax.annotation.Nonnull

  public URI getLandingPageUrl() {
    return landingPageUrl;
  }


  public void setLandingPageUrl(URI landingPageUrl) {
    this.landingPageUrl = landingPageUrl;
  }


  public AdaptiveAttributes layouts(List<LayoutsEnum> layouts) {
    
    this.layouts = layouts;
    return this;
  }

  public AdaptiveAttributes addLayoutsItem(LayoutsEnum layoutsItem) {
    this.layouts.add(layoutsItem);
    return this;
  }

   /**
   * The Adaptive layouts that are enabled.  It can contain any of the following values: \&quot;Editorial\&quot;, “Montage“, \&quot;InBannerVideo\&quot;.
   * @return layouts
  **/
  @javax.annotation.Nonnull

  public List<LayoutsEnum> getLayouts() {
    return layouts;
  }


  public void setLayouts(List<LayoutsEnum> layouts) {
    this.layouts = layouts;
  }


  public AdaptiveAttributes logos(List<ImageShape> logos) {
    
    this.logos = logos;
    return this;
  }

  public AdaptiveAttributes addLogosItem(ImageShape logosItem) {
    this.logos.add(logosItem);
    return this;
  }

   /**
   * Logo images uploaded on demostatic.criteo.com when deploying and then static.criteo.net
   * @return logos
  **/
  @javax.annotation.Nonnull

  public List<ImageShape> getLogos() {
    return logos;
  }


  public void setLogos(List<ImageShape> logos) {
    this.logos = logos;
  }


  public AdaptiveAttributes videos(List<VideoDetail> videos) {
    
    this.videos = videos;
    return this;
  }

  public AdaptiveAttributes addVideosItem(VideoDetail videosItem) {
    if (this.videos == null) {
      this.videos = null;
    }
    this.videos.add(videosItem);
    return this;
  }

   /**
   * Multiple videos potentially in different shapes.
   * @return videos
  **/
  @javax.annotation.Nullable

  public List<VideoDetail> getVideos() {
    return videos;
  }


  public void setVideos(List<VideoDetail> videos) {
    this.videos = videos;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AdaptiveAttributes instance itself
   */
  public AdaptiveAttributes putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdaptiveAttributes adaptiveAttributes = (AdaptiveAttributes) o;
    return Objects.equals(this.callsToAction, adaptiveAttributes.callsToAction) &&
        Objects.equals(this.colors, adaptiveAttributes.colors) &&
        Objects.equals(this.descriptionFont, adaptiveAttributes.descriptionFont) &&
        Objects.equals(this.descriptionText, adaptiveAttributes.descriptionText) &&
        Objects.equals(this.headlineFont, adaptiveAttributes.headlineFont) &&
        Objects.equals(this.headlineText, adaptiveAttributes.headlineText) &&
        Objects.equals(this.imageDisplay, adaptiveAttributes.imageDisplay) &&
        Objects.equals(this.imageSets, adaptiveAttributes.imageSets) &&
        Objects.equals(this.landingPageUrl, adaptiveAttributes.landingPageUrl) &&
        Objects.equals(this.layouts, adaptiveAttributes.layouts) &&
        Objects.equals(this.logos, adaptiveAttributes.logos) &&
        Objects.equals(this.videos, adaptiveAttributes.videos)&&
        Objects.equals(this.additionalProperties, adaptiveAttributes.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(callsToAction, colors, descriptionFont, descriptionText, headlineFont, headlineText, imageDisplay, imageSets, landingPageUrl, layouts, logos, videos, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdaptiveAttributes {\n");
    sb.append("    callsToAction: ").append(toIndentedString(callsToAction)).append("\n");
    sb.append("    colors: ").append(toIndentedString(colors)).append("\n");
    sb.append("    descriptionFont: ").append(toIndentedString(descriptionFont)).append("\n");
    sb.append("    descriptionText: ").append(toIndentedString(descriptionText)).append("\n");
    sb.append("    headlineFont: ").append(toIndentedString(headlineFont)).append("\n");
    sb.append("    headlineText: ").append(toIndentedString(headlineText)).append("\n");
    sb.append("    imageDisplay: ").append(toIndentedString(imageDisplay)).append("\n");
    sb.append("    imageSets: ").append(toIndentedString(imageSets)).append("\n");
    sb.append("    landingPageUrl: ").append(toIndentedString(landingPageUrl)).append("\n");
    sb.append("    layouts: ").append(toIndentedString(layouts)).append("\n");
    sb.append("    logos: ").append(toIndentedString(logos)).append("\n");
    sb.append("    videos: ").append(toIndentedString(videos)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("callsToAction");
    openapiFields.add("colors");
    openapiFields.add("descriptionFont");
    openapiFields.add("descriptionText");
    openapiFields.add("headlineFont");
    openapiFields.add("headlineText");
    openapiFields.add("imageDisplay");
    openapiFields.add("imageSets");
    openapiFields.add("landingPageUrl");
    openapiFields.add("layouts");
    openapiFields.add("logos");
    openapiFields.add("videos");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("callsToAction");
    openapiRequiredFields.add("colors");
    openapiRequiredFields.add("descriptionFont");
    openapiRequiredFields.add("descriptionText");
    openapiRequiredFields.add("headlineFont");
    openapiRequiredFields.add("headlineText");
    openapiRequiredFields.add("landingPageUrl");
    openapiRequiredFields.add("layouts");
    openapiRequiredFields.add("logos");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AdaptiveAttributes
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AdaptiveAttributes.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AdaptiveAttributes is not found in the empty JSON string", AdaptiveAttributes.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AdaptiveAttributes.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the required json array is present
      if (jsonObj.get("callsToAction") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("callsToAction").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `callsToAction` to be an array in the JSON string but got `%s`", jsonObj.get("callsToAction").toString()));
      }
      // validate the required field `colors`
      AdaptiveColors.validateJsonObject(jsonObj.getAsJsonObject("colors"));
      if (!jsonObj.get("descriptionFont").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `descriptionFont` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descriptionFont").toString()));
      }
      if (!jsonObj.get("descriptionText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `descriptionText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descriptionText").toString()));
      }
      if (!jsonObj.get("headlineFont").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `headlineFont` to be a primitive type in the JSON string but got `%s`", jsonObj.get("headlineFont").toString()));
      }
      if (!jsonObj.get("headlineText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `headlineText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("headlineText").toString()));
      }
      if ((jsonObj.get("imageDisplay") != null && !jsonObj.get("imageDisplay").isJsonNull()) && !jsonObj.get("imageDisplay").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `imageDisplay` to be a primitive type in the JSON string but got `%s`", jsonObj.get("imageDisplay").toString()));
      }
      if (jsonObj.get("imageSets") != null && !jsonObj.get("imageSets").isJsonNull()) {
        JsonArray jsonArrayimageSets = jsonObj.getAsJsonArray("imageSets");
        if (jsonArrayimageSets != null) {
          // ensure the json data is an array
          if (!jsonObj.get("imageSets").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `imageSets` to be an array in the JSON string but got `%s`", jsonObj.get("imageSets").toString()));
          }

          // validate the optional field `imageSets` (array)
          for (int i = 0; i < jsonArrayimageSets.size(); i++) {
            ImageSet.validateJsonObject(jsonArrayimageSets.get(i).getAsJsonObject());
          };
        }
      }
      if (!jsonObj.get("landingPageUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `landingPageUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("landingPageUrl").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("layouts") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("layouts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `layouts` to be an array in the JSON string but got `%s`", jsonObj.get("layouts").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("logos").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `logos` to be an array in the JSON string but got `%s`", jsonObj.get("logos").toString()));
      }

      JsonArray jsonArraylogos = jsonObj.getAsJsonArray("logos");
      // validate the required field `logos` (array)
      for (int i = 0; i < jsonArraylogos.size(); i++) {
        ImageShape.validateJsonObject(jsonArraylogos.get(i).getAsJsonObject());
      };
      if (jsonObj.get("videos") != null && !jsonObj.get("videos").isJsonNull()) {
        JsonArray jsonArrayvideos = jsonObj.getAsJsonArray("videos");
        if (jsonArrayvideos != null) {
          // ensure the json data is an array
          if (!jsonObj.get("videos").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `videos` to be an array in the JSON string but got `%s`", jsonObj.get("videos").toString()));
          }

          // validate the optional field `videos` (array)
          for (int i = 0; i < jsonArrayvideos.size(); i++) {
            VideoDetail.validateJsonObject(jsonArrayvideos.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdaptiveAttributes.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdaptiveAttributes' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdaptiveAttributes> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdaptiveAttributes.class));

       return (TypeAdapter<T>) new TypeAdapter<AdaptiveAttributes>() {
           @Override
           public void write(JsonWriter out, AdaptiveAttributes value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AdaptiveAttributes read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             AdaptiveAttributes instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AdaptiveAttributes given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AdaptiveAttributes
  * @throws IOException if the JSON string is invalid with respect to AdaptiveAttributes
  */
  public static AdaptiveAttributes fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AdaptiveAttributes.class);
  }

 /**
  * Convert an instance of AdaptiveAttributes to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

