/*
 * Criteo API
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: 2026-07
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.retailmedia.v2026_07.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.criteo.api.retailmedia.v2026_07.JSON;

/**
 * Array-valued constraints for performance DSP analytics. Exactly one of accountIds, campaignIds, or lineItemIds is required.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PerformanceReportFilters {
  public static final String SERIALIZED_NAME_ACCOUNT_IDS = "accountIds";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_IDS)
  private List<String> accountIds = null;

  /**
   * Gets or Sets activationPlatforms
   */
  @JsonAdapter(ActivationPlatformsEnum.Adapter.class)
  public enum ActivationPlatformsEnum {
    COMMERCEMAX("CommerceMax"),
    
    PRIVATEMARKET("PrivateMarket");

    private String value;

    ActivationPlatformsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ActivationPlatformsEnum fromValue(String value) {
      for (ActivationPlatformsEnum b : ActivationPlatformsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ActivationPlatformsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ActivationPlatformsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ActivationPlatformsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ActivationPlatformsEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ACTIVATION_PLATFORMS = "activationPlatforms";
  @SerializedName(SERIALIZED_NAME_ACTIVATION_PLATFORMS)
  private List<ActivationPlatformsEnum> activationPlatforms = null;

  /**
   * Gets or Sets budgetModels
   */
  @JsonAdapter(BudgetModelsEnum.Adapter.class)
  public enum BudgetModelsEnum {
    CRITEOBUDGET("CriteoBudget"),
    
    RETAILERBUDGET("RetailerBudget");

    private String value;

    BudgetModelsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BudgetModelsEnum fromValue(String value) {
      for (BudgetModelsEnum b : BudgetModelsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<BudgetModelsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BudgetModelsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BudgetModelsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BudgetModelsEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_BUDGET_MODELS = "budgetModels";
  @SerializedName(SERIALIZED_NAME_BUDGET_MODELS)
  private List<BudgetModelsEnum> budgetModels = null;

  /**
   * Gets or Sets buyTypes
   */
  @JsonAdapter(BuyTypesEnum.Adapter.class)
  public enum BuyTypesEnum {
    AUCTION("auction"),
    
    PREFERREDDEALS("preferredDeals"),
    
    SPONSORSHIP("sponsorship");

    private String value;

    BuyTypesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BuyTypesEnum fromValue(String value) {
      for (BuyTypesEnum b : BuyTypesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<BuyTypesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BuyTypesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BuyTypesEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BuyTypesEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_BUY_TYPES = "buyTypes";
  @SerializedName(SERIALIZED_NAME_BUY_TYPES)
  private List<BuyTypesEnum> buyTypes = null;

  public static final String SERIALIZED_NAME_CAMPAIGN_IDS = "campaignIds";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_IDS)
  private List<String> campaignIds = null;

  /**
   * Gets or Sets campaignTypes
   */
  @JsonAdapter(CampaignTypesEnum.Adapter.class)
  public enum CampaignTypesEnum {
    ALL("all"),
    
    SPONSOREDPRODUCTS("sponsoredProducts"),
    
    ONSITEDISPLAYS("onSiteDisplays");

    private String value;

    CampaignTypesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CampaignTypesEnum fromValue(String value) {
      for (CampaignTypesEnum b : CampaignTypesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CampaignTypesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CampaignTypesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CampaignTypesEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CampaignTypesEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CAMPAIGN_TYPES = "campaignTypes";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_TYPES)
  private List<CampaignTypesEnum> campaignTypes = null;

  public static final String SERIALIZED_NAME_LINE_ITEM_IDS = "lineItemIds";
  @SerializedName(SERIALIZED_NAME_LINE_ITEM_IDS)
  private List<String> lineItemIds = null;

  /**
   * Gets or Sets mediaTypes
   */
  @JsonAdapter(MediaTypesEnum.Adapter.class)
  public enum MediaTypesEnum {
    UNKNOWN("unknown"),
    
    VIDEO("video"),
    
    DISPLAY("display"),
    
    ALL("all");

    private String value;

    MediaTypesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MediaTypesEnum fromValue(String value) {
      for (MediaTypesEnum b : MediaTypesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<MediaTypesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MediaTypesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MediaTypesEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return MediaTypesEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_MEDIA_TYPES = "mediaTypes";
  @SerializedName(SERIALIZED_NAME_MEDIA_TYPES)
  private List<MediaTypesEnum> mediaTypes = null;

  /**
   * Gets or Sets salesChannels
   */
  @JsonAdapter(SalesChannelsEnum.Adapter.class)
  public enum SalesChannelsEnum {
    ONLINE("online"),
    
    OFFLINE("offline"),
    
    ALL("all");

    private String value;

    SalesChannelsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SalesChannelsEnum fromValue(String value) {
      for (SalesChannelsEnum b : SalesChannelsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SalesChannelsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SalesChannelsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SalesChannelsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SalesChannelsEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SALES_CHANNELS = "salesChannels";
  @SerializedName(SERIALIZED_NAME_SALES_CHANNELS)
  private List<SalesChannelsEnum> salesChannels = null;

  /**
   * Gets or Sets searchTermTargetings
   */
  @JsonAdapter(SearchTermTargetingsEnum.Adapter.class)
  public enum SearchTermTargetingsEnum {
    UNKNOWN("unknown"),
    
    AUTOMATIC("automatic"),
    
    MANUAL("manual");

    private String value;

    SearchTermTargetingsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SearchTermTargetingsEnum fromValue(String value) {
      for (SearchTermTargetingsEnum b : SearchTermTargetingsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SearchTermTargetingsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SearchTermTargetingsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SearchTermTargetingsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SearchTermTargetingsEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEARCH_TERM_TARGETINGS = "searchTermTargetings";
  @SerializedName(SERIALIZED_NAME_SEARCH_TERM_TARGETINGS)
  private List<SearchTermTargetingsEnum> searchTermTargetings = null;

  /**
   * Gets or Sets searchTermTypes
   */
  @JsonAdapter(SearchTermTypesEnum.Adapter.class)
  public enum SearchTermTypesEnum {
    UNKNOWN("unknown"),
    
    SEARCHED("searched"),
    
    ENTERED("entered");

    private String value;

    SearchTermTypesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SearchTermTypesEnum fromValue(String value) {
      for (SearchTermTypesEnum b : SearchTermTypesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SearchTermTypesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SearchTermTypesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SearchTermTypesEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SearchTermTypesEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEARCH_TERM_TYPES = "searchTermTypes";
  @SerializedName(SERIALIZED_NAME_SEARCH_TERM_TYPES)
  private List<SearchTermTypesEnum> searchTermTypes = null;

  /**
   * Gets or Sets targetedKeywordTypes
   */
  @JsonAdapter(TargetedKeywordTypesEnum.Adapter.class)
  public enum TargetedKeywordTypesEnum {
    UNKNOWN("unknown"),
    
    GENERIC("generic"),
    
    BRANDED("branded"),
    
    CONQUESTING("conquesting");

    private String value;

    TargetedKeywordTypesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TargetedKeywordTypesEnum fromValue(String value) {
      for (TargetedKeywordTypesEnum b : TargetedKeywordTypesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TargetedKeywordTypesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TargetedKeywordTypesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TargetedKeywordTypesEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TargetedKeywordTypesEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TARGETED_KEYWORD_TYPES = "targetedKeywordTypes";
  @SerializedName(SERIALIZED_NAME_TARGETED_KEYWORD_TYPES)
  private List<TargetedKeywordTypesEnum> targetedKeywordTypes = null;

  public PerformanceReportFilters() {
  }

  public PerformanceReportFilters accountIds(List<String> accountIds) {
    
    this.accountIds = accountIds;
    return this;
  }

  public PerformanceReportFilters addAccountIdsItem(String accountIdsItem) {
    if (this.accountIds == null) {
      this.accountIds = new ArrayList<>();
    }
    this.accountIds.add(accountIdsItem);
    return this;
  }

   /**
   * Get accountIds
   * @return accountIds
  **/
  @javax.annotation.Nullable

  public List<String> getAccountIds() {
    return accountIds;
  }


  public void setAccountIds(List<String> accountIds) {
    this.accountIds = accountIds;
  }


  public PerformanceReportFilters activationPlatforms(List<ActivationPlatformsEnum> activationPlatforms) {
    
    this.activationPlatforms = activationPlatforms;
    return this;
  }

  public PerformanceReportFilters addActivationPlatformsItem(ActivationPlatformsEnum activationPlatformsItem) {
    if (this.activationPlatforms == null) {
      this.activationPlatforms = new ArrayList<>();
    }
    this.activationPlatforms.add(activationPlatformsItem);
    return this;
  }

   /**
   * Get activationPlatforms
   * @return activationPlatforms
  **/
  @javax.annotation.Nullable

  public List<ActivationPlatformsEnum> getActivationPlatforms() {
    return activationPlatforms;
  }


  public void setActivationPlatforms(List<ActivationPlatformsEnum> activationPlatforms) {
    this.activationPlatforms = activationPlatforms;
  }


  public PerformanceReportFilters budgetModels(List<BudgetModelsEnum> budgetModels) {
    
    this.budgetModels = budgetModels;
    return this;
  }

  public PerformanceReportFilters addBudgetModelsItem(BudgetModelsEnum budgetModelsItem) {
    if (this.budgetModels == null) {
      this.budgetModels = new ArrayList<>();
    }
    this.budgetModels.add(budgetModelsItem);
    return this;
  }

   /**
   * Get budgetModels
   * @return budgetModels
  **/
  @javax.annotation.Nullable

  public List<BudgetModelsEnum> getBudgetModels() {
    return budgetModels;
  }


  public void setBudgetModels(List<BudgetModelsEnum> budgetModels) {
    this.budgetModels = budgetModels;
  }


  public PerformanceReportFilters buyTypes(List<BuyTypesEnum> buyTypes) {
    
    this.buyTypes = buyTypes;
    return this;
  }

  public PerformanceReportFilters addBuyTypesItem(BuyTypesEnum buyTypesItem) {
    if (this.buyTypes == null) {
      this.buyTypes = new ArrayList<>();
    }
    this.buyTypes.add(buyTypesItem);
    return this;
  }

   /**
   * Get buyTypes
   * @return buyTypes
  **/
  @javax.annotation.Nullable

  public List<BuyTypesEnum> getBuyTypes() {
    return buyTypes;
  }


  public void setBuyTypes(List<BuyTypesEnum> buyTypes) {
    this.buyTypes = buyTypes;
  }


  public PerformanceReportFilters campaignIds(List<String> campaignIds) {
    
    this.campaignIds = campaignIds;
    return this;
  }

  public PerformanceReportFilters addCampaignIdsItem(String campaignIdsItem) {
    if (this.campaignIds == null) {
      this.campaignIds = new ArrayList<>();
    }
    this.campaignIds.add(campaignIdsItem);
    return this;
  }

   /**
   * Get campaignIds
   * @return campaignIds
  **/
  @javax.annotation.Nullable

  public List<String> getCampaignIds() {
    return campaignIds;
  }


  public void setCampaignIds(List<String> campaignIds) {
    this.campaignIds = campaignIds;
  }


  public PerformanceReportFilters campaignTypes(List<CampaignTypesEnum> campaignTypes) {
    
    this.campaignTypes = campaignTypes;
    return this;
  }

  public PerformanceReportFilters addCampaignTypesItem(CampaignTypesEnum campaignTypesItem) {
    if (this.campaignTypes == null) {
      this.campaignTypes = new ArrayList<>();
    }
    this.campaignTypes.add(campaignTypesItem);
    return this;
  }

   /**
   * Get campaignTypes
   * @return campaignTypes
  **/
  @javax.annotation.Nullable

  public List<CampaignTypesEnum> getCampaignTypes() {
    return campaignTypes;
  }


  public void setCampaignTypes(List<CampaignTypesEnum> campaignTypes) {
    this.campaignTypes = campaignTypes;
  }


  public PerformanceReportFilters lineItemIds(List<String> lineItemIds) {
    
    this.lineItemIds = lineItemIds;
    return this;
  }

  public PerformanceReportFilters addLineItemIdsItem(String lineItemIdsItem) {
    if (this.lineItemIds == null) {
      this.lineItemIds = new ArrayList<>();
    }
    this.lineItemIds.add(lineItemIdsItem);
    return this;
  }

   /**
   * Get lineItemIds
   * @return lineItemIds
  **/
  @javax.annotation.Nullable

  public List<String> getLineItemIds() {
    return lineItemIds;
  }


  public void setLineItemIds(List<String> lineItemIds) {
    this.lineItemIds = lineItemIds;
  }


  public PerformanceReportFilters mediaTypes(List<MediaTypesEnum> mediaTypes) {
    
    this.mediaTypes = mediaTypes;
    return this;
  }

  public PerformanceReportFilters addMediaTypesItem(MediaTypesEnum mediaTypesItem) {
    if (this.mediaTypes == null) {
      this.mediaTypes = new ArrayList<>();
    }
    this.mediaTypes.add(mediaTypesItem);
    return this;
  }

   /**
   * Get mediaTypes
   * @return mediaTypes
  **/
  @javax.annotation.Nullable

  public List<MediaTypesEnum> getMediaTypes() {
    return mediaTypes;
  }


  public void setMediaTypes(List<MediaTypesEnum> mediaTypes) {
    this.mediaTypes = mediaTypes;
  }


  public PerformanceReportFilters salesChannels(List<SalesChannelsEnum> salesChannels) {
    
    this.salesChannels = salesChannels;
    return this;
  }

  public PerformanceReportFilters addSalesChannelsItem(SalesChannelsEnum salesChannelsItem) {
    if (this.salesChannels == null) {
      this.salesChannels = new ArrayList<>();
    }
    this.salesChannels.add(salesChannelsItem);
    return this;
  }

   /**
   * Get salesChannels
   * @return salesChannels
  **/
  @javax.annotation.Nullable

  public List<SalesChannelsEnum> getSalesChannels() {
    return salesChannels;
  }


  public void setSalesChannels(List<SalesChannelsEnum> salesChannels) {
    this.salesChannels = salesChannels;
  }


  public PerformanceReportFilters searchTermTargetings(List<SearchTermTargetingsEnum> searchTermTargetings) {
    
    this.searchTermTargetings = searchTermTargetings;
    return this;
  }

  public PerformanceReportFilters addSearchTermTargetingsItem(SearchTermTargetingsEnum searchTermTargetingsItem) {
    if (this.searchTermTargetings == null) {
      this.searchTermTargetings = new ArrayList<>();
    }
    this.searchTermTargetings.add(searchTermTargetingsItem);
    return this;
  }

   /**
   * Get searchTermTargetings
   * @return searchTermTargetings
  **/
  @javax.annotation.Nullable

  public List<SearchTermTargetingsEnum> getSearchTermTargetings() {
    return searchTermTargetings;
  }


  public void setSearchTermTargetings(List<SearchTermTargetingsEnum> searchTermTargetings) {
    this.searchTermTargetings = searchTermTargetings;
  }


  public PerformanceReportFilters searchTermTypes(List<SearchTermTypesEnum> searchTermTypes) {
    
    this.searchTermTypes = searchTermTypes;
    return this;
  }

  public PerformanceReportFilters addSearchTermTypesItem(SearchTermTypesEnum searchTermTypesItem) {
    if (this.searchTermTypes == null) {
      this.searchTermTypes = new ArrayList<>();
    }
    this.searchTermTypes.add(searchTermTypesItem);
    return this;
  }

   /**
   * Get searchTermTypes
   * @return searchTermTypes
  **/
  @javax.annotation.Nullable

  public List<SearchTermTypesEnum> getSearchTermTypes() {
    return searchTermTypes;
  }


  public void setSearchTermTypes(List<SearchTermTypesEnum> searchTermTypes) {
    this.searchTermTypes = searchTermTypes;
  }


  public PerformanceReportFilters targetedKeywordTypes(List<TargetedKeywordTypesEnum> targetedKeywordTypes) {
    
    this.targetedKeywordTypes = targetedKeywordTypes;
    return this;
  }

  public PerformanceReportFilters addTargetedKeywordTypesItem(TargetedKeywordTypesEnum targetedKeywordTypesItem) {
    if (this.targetedKeywordTypes == null) {
      this.targetedKeywordTypes = new ArrayList<>();
    }
    this.targetedKeywordTypes.add(targetedKeywordTypesItem);
    return this;
  }

   /**
   * Get targetedKeywordTypes
   * @return targetedKeywordTypes
  **/
  @javax.annotation.Nullable

  public List<TargetedKeywordTypesEnum> getTargetedKeywordTypes() {
    return targetedKeywordTypes;
  }


  public void setTargetedKeywordTypes(List<TargetedKeywordTypesEnum> targetedKeywordTypes) {
    this.targetedKeywordTypes = targetedKeywordTypes;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PerformanceReportFilters instance itself
   */
  public PerformanceReportFilters putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PerformanceReportFilters performanceReportFilters = (PerformanceReportFilters) o;
    return Objects.equals(this.accountIds, performanceReportFilters.accountIds) &&
        Objects.equals(this.activationPlatforms, performanceReportFilters.activationPlatforms) &&
        Objects.equals(this.budgetModels, performanceReportFilters.budgetModels) &&
        Objects.equals(this.buyTypes, performanceReportFilters.buyTypes) &&
        Objects.equals(this.campaignIds, performanceReportFilters.campaignIds) &&
        Objects.equals(this.campaignTypes, performanceReportFilters.campaignTypes) &&
        Objects.equals(this.lineItemIds, performanceReportFilters.lineItemIds) &&
        Objects.equals(this.mediaTypes, performanceReportFilters.mediaTypes) &&
        Objects.equals(this.salesChannels, performanceReportFilters.salesChannels) &&
        Objects.equals(this.searchTermTargetings, performanceReportFilters.searchTermTargetings) &&
        Objects.equals(this.searchTermTypes, performanceReportFilters.searchTermTypes) &&
        Objects.equals(this.targetedKeywordTypes, performanceReportFilters.targetedKeywordTypes)&&
        Objects.equals(this.additionalProperties, performanceReportFilters.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountIds, activationPlatforms, budgetModels, buyTypes, campaignIds, campaignTypes, lineItemIds, mediaTypes, salesChannels, searchTermTargetings, searchTermTypes, targetedKeywordTypes, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PerformanceReportFilters {\n");
    sb.append("    accountIds: ").append(toIndentedString(accountIds)).append("\n");
    sb.append("    activationPlatforms: ").append(toIndentedString(activationPlatforms)).append("\n");
    sb.append("    budgetModels: ").append(toIndentedString(budgetModels)).append("\n");
    sb.append("    buyTypes: ").append(toIndentedString(buyTypes)).append("\n");
    sb.append("    campaignIds: ").append(toIndentedString(campaignIds)).append("\n");
    sb.append("    campaignTypes: ").append(toIndentedString(campaignTypes)).append("\n");
    sb.append("    lineItemIds: ").append(toIndentedString(lineItemIds)).append("\n");
    sb.append("    mediaTypes: ").append(toIndentedString(mediaTypes)).append("\n");
    sb.append("    salesChannels: ").append(toIndentedString(salesChannels)).append("\n");
    sb.append("    searchTermTargetings: ").append(toIndentedString(searchTermTargetings)).append("\n");
    sb.append("    searchTermTypes: ").append(toIndentedString(searchTermTypes)).append("\n");
    sb.append("    targetedKeywordTypes: ").append(toIndentedString(targetedKeywordTypes)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accountIds");
    openapiFields.add("activationPlatforms");
    openapiFields.add("budgetModels");
    openapiFields.add("buyTypes");
    openapiFields.add("campaignIds");
    openapiFields.add("campaignTypes");
    openapiFields.add("lineItemIds");
    openapiFields.add("mediaTypes");
    openapiFields.add("salesChannels");
    openapiFields.add("searchTermTargetings");
    openapiFields.add("searchTermTypes");
    openapiFields.add("targetedKeywordTypes");
    openapiFields.add("accountIds");
    openapiFields.add("activationPlatforms");
    openapiFields.add("budgetModels");
    openapiFields.add("buyTypes");
    openapiFields.add("campaignIds");
    openapiFields.add("campaignTypes");
    openapiFields.add("lineItemIds");
    openapiFields.add("mediaTypes");
    openapiFields.add("salesChannels");
    openapiFields.add("searchTermTargetings");
    openapiFields.add("searchTermTypes");
    openapiFields.add("targetedKeywordTypes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PerformanceReportFilters
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PerformanceReportFilters.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PerformanceReportFilters is not found in the empty JSON string", PerformanceReportFilters.openapiRequiredFields.toString()));
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("accountIds") != null && !jsonObj.get("accountIds").isJsonNull() && !jsonObj.get("accountIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `accountIds` to be an array in the JSON string but got `%s`", jsonObj.get("accountIds").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("activationPlatforms") != null && !jsonObj.get("activationPlatforms").isJsonNull() && !jsonObj.get("activationPlatforms").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `activationPlatforms` to be an array in the JSON string but got `%s`", jsonObj.get("activationPlatforms").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("budgetModels") != null && !jsonObj.get("budgetModels").isJsonNull() && !jsonObj.get("budgetModels").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `budgetModels` to be an array in the JSON string but got `%s`", jsonObj.get("budgetModels").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("buyTypes") != null && !jsonObj.get("buyTypes").isJsonNull() && !jsonObj.get("buyTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `buyTypes` to be an array in the JSON string but got `%s`", jsonObj.get("buyTypes").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("campaignIds") != null && !jsonObj.get("campaignIds").isJsonNull() && !jsonObj.get("campaignIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `campaignIds` to be an array in the JSON string but got `%s`", jsonObj.get("campaignIds").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("campaignTypes") != null && !jsonObj.get("campaignTypes").isJsonNull() && !jsonObj.get("campaignTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `campaignTypes` to be an array in the JSON string but got `%s`", jsonObj.get("campaignTypes").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("lineItemIds") != null && !jsonObj.get("lineItemIds").isJsonNull() && !jsonObj.get("lineItemIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `lineItemIds` to be an array in the JSON string but got `%s`", jsonObj.get("lineItemIds").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("mediaTypes") != null && !jsonObj.get("mediaTypes").isJsonNull() && !jsonObj.get("mediaTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `mediaTypes` to be an array in the JSON string but got `%s`", jsonObj.get("mediaTypes").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("salesChannels") != null && !jsonObj.get("salesChannels").isJsonNull() && !jsonObj.get("salesChannels").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `salesChannels` to be an array in the JSON string but got `%s`", jsonObj.get("salesChannels").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("searchTermTargetings") != null && !jsonObj.get("searchTermTargetings").isJsonNull() && !jsonObj.get("searchTermTargetings").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `searchTermTargetings` to be an array in the JSON string but got `%s`", jsonObj.get("searchTermTargetings").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("searchTermTypes") != null && !jsonObj.get("searchTermTypes").isJsonNull() && !jsonObj.get("searchTermTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `searchTermTypes` to be an array in the JSON string but got `%s`", jsonObj.get("searchTermTypes").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("targetedKeywordTypes") != null && !jsonObj.get("targetedKeywordTypes").isJsonNull() && !jsonObj.get("targetedKeywordTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `targetedKeywordTypes` to be an array in the JSON string but got `%s`", jsonObj.get("targetedKeywordTypes").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PerformanceReportFilters.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PerformanceReportFilters' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PerformanceReportFilters> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PerformanceReportFilters.class));

       return (TypeAdapter<T>) new TypeAdapter<PerformanceReportFilters>() {
           @Override
           public void write(JsonWriter out, PerformanceReportFilters value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PerformanceReportFilters read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PerformanceReportFilters instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PerformanceReportFilters given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PerformanceReportFilters
  * @throws IOException if the JSON string is invalid with respect to PerformanceReportFilters
  */
  public static PerformanceReportFilters fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PerformanceReportFilters.class);
  }

 /**
  * Convert an instance of PerformanceReportFilters to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

