apply plugin: 'helper'
apply plugin: 'org.openapi.generator'

def clientOutputDir = "$rootDir/$rootProject.generatedClientsDirName/java"
def clientOutputDirTestOnly = "$rootDir/$rootProject.generatedClientsDirNameTestOnly/java"
def technologyStack = "java8"
def nameSeparator = '.'

def cleanPreviousDist = registerCleanPreviousDistTask(tasks, [clientOutputDir, clientOutputDirTestOnly])

def taskList = [cleanPreviousDist];

def specsWithOutputRoot = rootProject.swaggerSourceList.collect { [it, clientOutputDir, 'generatorConfiguration.yaml'] } +
                          rootProject.swaggerSourceListTestOnly.collect { [it, clientOutputDirTestOnly, 'generatorConfigurationTestOnly.yaml'] }
specsWithOutputRoot.each { specFile, outputRoot, generatorConfigurationFileName ->
    def helper = new JavaHelper(project, technologyStack, outputRoot, nameSeparator, specFile)

    def isExperimental = helper.criteoApiVersion == 'experimental';
    def artifactId = isExperimental ? "criteo-api-${helper.criteoService}-sdk-experimental" : "criteo-api-${helper.criteoService}-sdk"

    // useful when you want templates to be part of the SDK generated
    def sdkMainDir = 'src/main/java/com/criteo/api/' + helper.criteoService + '/' + helper.versionInNamespace
    def sdkTestDir = 'src/test/java/com/criteo/api/' + helper.criteoService + '/' + helper.versionInNamespace

    def configDir = "${helper.temporaryBuildDirArtifacts}/${helper.parsedApiName}"
    def generatedConfigFile = "${helper.criteoService}-${helper.versionInNamespace}.yaml"
    def createConfig = helper.registerCreateConfigTask(generatorConfigurationFileName, configDir, generatedConfigFile, sdkMainDir, sdkTestDir)

    def generateTask = helper.registerOpenApiGenerateTask(helper.language, "${configDir}/${generatedConfigFile}", [
            apiPackage               : "${helper.namespaceBase}.api", // com.criteo.api.marketingsolutions.v2021_10.api
            modelPackage             : "${helper.namespaceBase}.model",
            artifactDescription      : "${helper.language.toUpperCase()} SDK for Criteo API ${helper.criteoService} for ${helper.criteoApiVersion} version",
            artifactId               : artifactId, // criteo-api-marketingsolutions-sdk (or criteo-api-marketingsolutions-sdk-experimental)
            artifactVersion          : helper.artifactVersion, // 2021.10.0.211110
            artifactUrl              : "https://github.com/criteo/criteo-api-${helper.language}-sdk",
            dateLibrary              : technologyStack,
            developerName            : 'Criteo',
            developerEmail           : 'public-api-maintainers@criteois.com',
            developerOrganization    : 'Criteo',
            developerOrganizationUrl : 'https://www.criteo.com/',
            licenseName              : 'Apache License, version 2.0',
            licenseUrl               : 'https://www.apache.org/licenses/LICENSE-2.0.txt',
            scmConnection            : "scm:git:git://github.com/criteo/criteo-api-${helper.language}-sdk.git",
            scmDeveloperConnection   : "scm:git:ssh://github.com:criteo/criteo-api-${helper.language}-sdk.git",
            scmUrl                   : "https://github.com/criteo/criteo-api-${helper.language}-sdk",
            disallowAdditionalPropertiesIfNotPresent : 'false',
    ]
    )
    generateTask.configure {
        additionalProperties.putAll([
                sdkTestDir: "${sdkTestDir}",
        ])
        dependsOn(createConfig)
    }

    taskList << helper.registerCopyLicenseTask()
    taskList << helper.registerRemoveUnwantedFilesTasks([ '.openapi-generator-ignore', '.travis.yml', 'git_push.sh', 'build.sbt', 'src/main/AndroidManifest.xml', 'gradle.properties', 'pom.xml'])
    taskList << generateTask
}

tasks.register("generateClient") {
    group = 'Criteo'
    description = "Generate the ${technologyStack.toUpperCase()} client using openapi-generator and custom templates".toString()
    dependsOn(taskList)
}

class JavaHelper extends Helper {

    JavaHelper(Object project, String technologyStack, String clientOutputDir, Object nameSeparator, File swaggerFile) {
        super(project, technologyStack, clientOutputDir, nameSeparator, swaggerFile)
        namespaceBase = "com." + super.namespaceBase; // 'com' is Java-specific => example: com.criteo.api.marketingsolutions.v2021_10
    }
}