files:
  ApiClientBuilder.mustache:
    folder: sdkFolder
    destinationFilename: ApiClientBuilder.java
  GatewayApiTest.mustache:
    folder : src/test/java/com/criteo.api.sdk
    templateType: SupportingFiles
    destinationFilename: GatewayApiTest.java
  OAuthApiTest.mustache:
    folder : src/test/java/com/criteo.api.sdk
    templateType: SupportingFiles
    destinationFilename: OAuthApiTest.java
  PortfolioApplicationExample.mustache:
    folder: src/examples/java/criteo/api/examples
    templateType: SupportingFiles
    destinationFilename: PortfolioApplication.java
  StatisticsApplicationExample.mustache:
    folder: src/examples/java/criteo/api/examples
    templateType: SupportingFiles
    destinationFilename: StatisticsApplication.java