files:
  custom/ApiClientBuilder.java.mustache:
    folder: sdkFolder
    destinationFilename: ApiClientBuilder.java
  custom/GatewayApiTest.java.mustache:
    folder : testFolder
    templateType: SupportingFiles
    destinationFilename: GatewayApiTest.java
  custom/ExampleApplication.java.mustache:
    folder: testFolder
    templateType: SupportingFiles
    destinationFilename: ExampleApplication.java