files:
  GatewayApiTest.mustache:
    folder : src/test/java/com/criteo.api.sdk
    templateType: SupportingFiles
    destinationFilename: GatewayApiTest.java
  OAuthApiTest.mustache:
    folder : src/test/java/com/criteo.api.sdk
    templateType: SupportingFiles
    destinationFilename: OAuthApiTest.java
