files:
  ApiClientBuilder.mustache:
    folder: sdkFolder
    destinationFilename: ApiClientBuilder.java
  GatewayApiTest.mustache:
    folder : testFolder
    templateType: SupportingFiles
    destinationFilename: GatewayApiTest.java
  ExampleApplication.mustache:
    folder: testFolder
    templateType: SupportingFiles
    destinationFilename: ExampleApplication.java