apply plugin: 'helper'
apply plugin: 'java-library'
apply plugin: 'org.openapi.generator'

ext {
    jar.enabled = false
}

def clientOutputDir = "$rootDir/$rootProject.generatedClientsDirName/python"
def clientOutputDirTestOnly = "$rootDir/$rootProject.generatedClientsDirNameTestOnly/python"
def technologyStack = "python"
def nameSeparator = '_'

def cleanPreviousDist = registerCleanPreviousDistTask(tasks, [clientOutputDir, clientOutputDirTestOnly])

def taskList = [cleanPreviousDist];

def specsWithOutputRoot = rootProject.swaggerSourceList.collect { [it, clientOutputDir, 'generatorConfiguration.yaml'] } +
                          rootProject.swaggerSourceListTestOnly.collect { [it, clientOutputDirTestOnly, 'generatorConfigurationTestOnly.yaml'] }
specsWithOutputRoot.each { specFile, outputRoot, generatorConfigurationFileName ->
    def helper = new Helper(project, technologyStack, outputRoot, nameSeparator, specFile)
    def configDir = "${helper.temporaryBuildDirArtifacts}/${helper.parsedApiName}"
    def generatedConfigFile = "${helper.namespaceBase}.yaml"
    def createConfig = helper.registerCreateConfigTask(generatorConfigurationFileName, configDir, generatedConfigFile, helper.namespaceBase)

    def generateTask = helper.registerOpenApiGenerateTask("python-prior", "${configDir}/${generatedConfigFile}", [
            apiVersion              : helper.artifactVersion,
            artifactId              : "criteo-api-${helper.criteoService}-sdk",
            description             : "${helper.language.toUpperCase()} SDK for Criteo API ${helper.criteoService} for ${helper.criteoApiVersion} version",
            invokerPackage          : 'Criteo\\SDK',
            packageName             : helper.namespaceBase,
            packageUrl              : "https://github.com/criteo/criteo-api-${helper.language}-sdk",
            packageVersion          : helper.artifactVersion, // v2021_10.1.211109
            projectName             : "criteo-api-${helper.criteoService}-sdk",
    ]
    )
    generateTask.configure {
        dependsOn createConfig
    }

    taskList << helper.registerCopyLicenseTask()
    taskList << helper.registerRemoveUnwantedFilesTasks(['.openapi-generator-ignore', '.travis.yml', 'git_push.sh'])
    taskList << generateTask
    taskList << createConfig
}


tasks.register("generateClient") {
    group = 'Criteo'
    description = "Generate the ${technologyStack.toUpperCase()} client using openapi-generator and custom templates".toString()
    dependsOn(taskList)
}
