files:
  test_gateway_api.mustache:
    folder : test
    templateType: SupportingFiles
    destinationFilename: test_gateway_api.py
  test_oauth_api.mustache:
    folder : test
    templateType: SupportingFiles
    destinationFilename: test_oauth_api.py