files:
  api_client_builder.mustache:
    destinationFilename: api_client_builder.py
    folder : %sdkFolder%
    templateType : SupportingFiles
  criteo_api_client.mustache:
    destinationFilename: criteo_api_client.py
    folder : %sdkFolder%
    templateType : SupportingFiles
  criteo_rest.mustache:
    destinationFilename: criteo_rest.py
    folder : %sdkFolder%
    templateType : SupportingFiles
  criteo_auth.mustache:
    destinationFilename: criteo_auth.py
    folder : %sdkFolder%
    templateType : SupportingFiles
  test_gateway_api.mustache:
    folder : test
    templateType: SupportingFiles
    destinationFilename: test_gateway_api.py
  example_application.mustache:
    folder : test
    templateType: SupportingFiles
    destinationFilename: example_application.py