files:
  custom/api_client_builder.py.mustache:
    destinationFilename: api_client_builder.py
    folder : %sdkFolder%
    templateType : SupportingFiles
  custom/criteo_api_client.py.mustache:
    destinationFilename: criteo_api_client.py
    folder : %sdkFolder%
    templateType : SupportingFiles
  custom/criteo_rest.py.mustache:
    destinationFilename: criteo_rest.py
    folder : %sdkFolder%
    templateType : SupportingFiles
  custom/criteo_auth.py.mustache:
    destinationFilename: criteo_auth.py
    folder : %sdkFolder%
    templateType : SupportingFiles
  custom/flow_constants.py.mustache:
    destinationFilename: flow_constants.py
    folder : %sdkFolder%
    templateType : SupportingFiles    
  custom/test_gateway_api.py.mustache:
    folder : test
    templateType: SupportingFiles
    destinationFilename: test_gateway_api.py
  custom/example_application.py.mustache:
    folder : test
    templateType: SupportingFiles
    destinationFilename: example_application.py