files:
  test_gateway_api.mustache:
    folder : test
    templateType: SupportingFiles
    destinationFilename: test_gateway_api.py
  test_oauth_api.mustache:
    folder : test
    templateType: SupportingFiles
    destinationFilename: test_oauth_api.py
  example_init.mustache:
    folder : examples
    templateType: SupportingFiles
    destinationFilename: __init__.py  
  example_statistics.mustache:
    folder : examples
    templateType: SupportingFiles
    destinationFilename: statistics.py
  example_portfolio.mustache:
    folder : examples
    templateType: SupportingFiles
    destinationFilename: portfolio.py