static def getFormattedDate() {
    def date = new Date()
    def formattedDate = date.format('yyMMdd')
    return formattedDate
}

static def registerCleanPreviousDistTask(def tasks, String clientOutputDir) {
  return tasks.register("cleanPreviousDist", Delete) {
      group = 'Criteo'
      description = 'Clean up generated client output folder'

      delete clientOutputDir
      followSymlinks = true
  }
}

static def getArtifactVersion(String criteoApiVersion, String generatorVersion) {
    def isPreviewOrExperimental = criteoApiVersion == 'preview' || criteoApiVersion == 'experimental';
    def artifactVersion = isPreviewOrExperimental ? '0' : criteoApiVersion.replaceAll("_",".").toString()
    artifactVersion += ".${generatorVersion}.${getFormattedDate()}".toString() // example : 2021.01.0.211110 for stable , 0.0.211110 for preview
    return artifactVersion
}

static def registerCopyLicenseTask(def project, String technologyStack, String parsedApiName, String clientOutputDirPerVersion) {
    return project.tasks.register("copyLicense_${technologyStack}_${parsedApiName}", Copy) {
        group = 'Criteo'
        description = 'Copy the license into the client output folder'

        from "$project.projectDir/../LICENSE"
        into clientOutputDirPerVersion
        rename 'LICENSE', 'LICENSE.txt'
    };
}

static def registerRemoveUnwantedFilesTasks(def project, String technologyStack, String parsedApiName, String clientOutputDirPerVersion, Iterable<String> unwantedFiles) {
    return project.tasks.register("removeUnwantedFiles_" + technologyStack + "_" + parsedApiName, Delete) {
        group = 'Criteo'
        description = 'Remove files generated by openapi-generator that we don\'t want to push'

        delete project.fileTree(clientOutputDirPerVersion) {
            include unwantedFiles
        }
        followSymlinks = true
    }
}

static def registerCreateConfigTask(def project, String taskSuffix, String configDir, String destFileName, String sdkFolder="", String testFolder="") {
    return project.tasks.register("createConfig_${taskSuffix}", Copy) {
        from "${project.projectDir}/generatorConfiguration.yaml"
        into configDir
        rename { filename -> destFileName }
        filter { line -> line.replaceAll('%sdkFolder%', sdkFolder).replaceAll('%testFolder%', testFolder) }
    }
}

ext {
    registerCleanPreviousDistTask = this.&registerCleanPreviousDistTask
    getArtifactVersion = this.&getArtifactVersion
    registerCopyLicenseTask = this.&registerCopyLicenseTask
    registerRemoveUnwantedFilesTasks = this.&registerRemoveUnwantedFilesTasks
    registerCreateConfigTask = this.&registerCreateConfigTask
}
