import groovy.io.FileType

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
}

apply plugin: 'java-library'

static def getAllSwaggerFilesFromDir(String dirPath) {
    def ret = []
    def dir = new File(dirPath)

    if (dir.exists()) {
        dir.eachFileRecurse(FileType.FILES) { file ->
            if (file.getName().endsWith(".json"))
                ret << file
        }
    } else {
        throw new GradleException("Folder ${dirPath} doesn't exist")
    }

    if (ret.isEmpty()) {
        throw new GradleException("No swaggers found in ${dirPath} folder")
    }
    return ret
}

ext {
    artifactId = "criteo-client-generator"
    groupId = "com.criteo.api"
    version = '1.0.0'
    description = 'Criteo API Clients Generator'
    sourceCompatibility = '1.8'
    jar.enabled = false
    generatedClientsDirName = 'generated-sources'
    generatedClientsDirNameTestOnly = 'generated-sources-test-only'
    swaggerSourceList = getAllSwaggerFilesFromDir("$rootDir/api-specifications")
    swaggerSourceListTestOnly = getAllSwaggerFilesFromDir("$rootDir/api-specifications-test-only"); // Test-only specs: generated, but never pushed to the public SDK repositories nor to Postman.
}
