//import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

buildscript {
    repositories {
        mavenLocal()
        maven { url = "https://repo1.maven.org/maven2" }
    }
    dependencies {
        classpath "org.openapitools:openapi-generator-gradle-plugin:6.3.0"
    }
}

apply plugin: 'helper'
apply plugin: 'java-library'
apply plugin: 'org.openapi.generator'

ext {
    jar.enabled = false
}

def clientOutputDir = "$rootDir/$rootProject.generatedClientsDirName/php"
def criteoPackage = providers.gradleProperty("package.name.base").orNull
def generatorVersion = providers.gradleProperty("generator.version").orNull
def technologyStack = "php"
def nameSeparator = '\\'
def language = technologyStack.replaceAll(/[^a-zA-Z]/,"").toLowerCase()

def cleanPreviousDist = registerCleanPreviousDistTask(tasks, clientOutputDir)

task generateClient(type: GradleBuild) {
    group = 'Criteo'
    description = "Generate the ${language.toUpperCase()} client using openapi-generator and custom templates".toString()

    def taskList = [cleanPreviousDist];

	rootProject.swaggerSourceList.each {
        def parsedApiName = it.getName().replace(".json", "").toLowerCase();
        def (criteoService, apiVersionFromName) = parsedApiName.tokenize('_');
        def criteoApiVersion = apiVersionFromName.replace('-', '_');
        
        def clientOutputDirPerVersion = clientOutputDir + "/" + parsedApiName;
        def specPath = it.path;

        def versionInNamespace =  criteoApiVersion
        if (versionInNamespace.matches("[0-9].*"))
             versionInNamespace= "v" + versionInNamespace

        def namespaceBase = "${criteoPackage}.${criteoService}.${versionInNamespace}".replace('.', nameSeparator).toString(); // example: criteo\api\marketingsolutions\v2021_10

        def artifactVersion = getArtifactVersion(criteoApiVersion, generatorVersion)

        def generateTask = registerOpenApiGenerateTask(project, "${technologyStack}_${parsedApiName}", language, "$projectDir/generatorConfiguration.yaml", specPath, clientOutputDirPerVersion, criteoService, [
                        artifactVersion         : "${artifactVersion}".toString(),
                        invokerPackage          : "${namespaceBase}".toString(),
                        packageName             : "criteo-api-${criteoService}-sdk".toString(),
                ]
        )
        generateTask.configure {
            gitUserId = 'criteo'
            gitRepoId = "criteo-api-${criteoService}-${language}-sdk"
        }

        def copyLicense = registerCopyLicenseTask(project, technologyStack, parsedApiName, clientOutputDirPerVersion)

        def removeUnwantedFiles = registerRemoveUnwantedFilesTasks(project, technologyStack, parsedApiName, clientOutputDirPerVersion,
                ['.openapi-generator-ignore', '.travis.yml', 'git_push.sh']
        )

        taskList << generateTask.name
        taskList << copyLicense.name
        taskList << removeUnwantedFiles.name
    }

    generateClient.dependsOn(taskList);
}
