import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

buildscript {
    repositories {
        mavenLocal()
        maven { url = "https://repo1.maven.org/maven2" }
    }
    dependencies {
        classpath "org.openapitools:openapi-generator-gradle-plugin:6.3.0"
    }
}

apply plugin: 'helper'
apply plugin: 'java-library'
apply plugin: 'org.openapi.generator'

ext {
    jar.enabled = false
}

def clientOutputDir = "$rootDir/$rootProject.generatedClientsDirName/php"
def resourcesDir = "$projectDir/resources".toString()
def criteoPackage = providers.gradleProperty("package.name.base").orNull
def generatorVersion = providers.gradleProperty("generator.version").orNull
def technologyStack = "php"
def nameSeparator = '\\'
def language = technologyStack.replaceAll(/[^a-zA-Z]/,"").toLowerCase()

def cleanPreviousDist = registerCleanPreviousDistTask(tasks, clientOutputDir)

task generateClient(type: GradleBuild) {
    group = 'Criteo'
    description = "Generate the {language.toUpperCase()} client using openapi-generator and custom templates".toString()

    def taskList = [cleanPreviousDist];

	rootProject.swaggerSourceList.each {
        def parsedApiName = it.getName().replace(".json", "").toLowerCase();
        def (criteoService, apiVersionFromName) = parsedApiName.tokenize('_');
        def criteoApiVersion = apiVersionFromName.replace('-', '_');
        
        def clientOutputDirPerVersion = clientOutputDir + "/" + parsedApiName;
        def specPath = it.path;

        def versionInNamespace =  criteoApiVersion
        if (versionInNamespace.matches("[0-9].*"))
             versionInNamespace= "v" + versionInNamespace

        def namespaceBase = "${criteoPackage}.${criteoService}.${versionInNamespace}".replace('.', nameSeparator).toString(); // example: criteo\api\marketingsolutions\v2021_10

        def artifactVersion = getArtifactVersion(criteoApiVersion, generatorVersion)

        def generateTask = task("openApiGenerate_${technologyStack}_" + parsedApiName, type: GenerateTask.class) {
                configFile = "$projectDir/generatorConfiguration.yaml".toString()
                generatorName = "$language".toString()
                templateDir = "$resourcesDir/templates/".toString()
                inputSpec = specPath
                outputDir = clientOutputDirPerVersion
                removeOperationIdPrefix = true
                generateApiTests = false
                generateModelTests = false
                gitUserId = 'criteo'
                gitRepoId = "criteo-api-${criteoService}-${language}-sdk".toString()
                configOptions = [
                        groupId                 : 'criteo',
                        artifactVersion         : "${artifactVersion}".toString(),
                        hideGenerationTimestamp : 'true',
                        invokerPackage          : "${namespaceBase}".toString(),
                        packageName             : "criteo-api-${criteoService}-sdk".toString(),
                 ]
                additionalProperties = [
                        criteoServiceAsPrefix   : "${criteoService}".toString().toUpperCase(),                         
                ]
        }


        def copyLicense = registerCopyLicenseTask(project, technologyStack, parsedApiName, clientOutputDirPerVersion)

        def removeUnwantedFiles = task("removeUnwantedFiles_" + technologyStack + "_" + parsedApiName, type: Delete) {
            group = 'Criteo'
            description = 'Remove files generated by openapi-generator that we don\'t want to push'

            delete fileTree(clientOutputDirPerVersion) {
                include '.openapi-generator-ignore', '.travis.yml', 'git_push.sh'
            }
            followSymlinks = true
        }

        taskList << generateTask.name
        taskList << copyLicense.name
        taskList << removeUnwantedFiles.name
    }

    generateClient.dependsOn(taskList);
}
