apply plugin: 'helper'
apply plugin: 'java-library'
apply plugin: 'org.openapi.generator'

ext {
    jar.enabled = false
}

def clientOutputDir = "$rootDir/$rootProject.generatedClientsDirName/php"
def clientOutputDirTestOnly = "$rootDir/$rootProject.generatedClientsDirNameTestOnly/php"
def technologyStack = "php"
def nameSeparator = '\\'

def cleanPreviousDist = registerCleanPreviousDistTask(tasks, [clientOutputDir, clientOutputDirTestOnly])

def taskList = [cleanPreviousDist];

def specsWithOutputRoot = rootProject.swaggerSourceList.collect { [it, clientOutputDir, 'generatorConfiguration.yaml'] } +
                          rootProject.swaggerSourceListTestOnly.collect { [it, clientOutputDirTestOnly, 'generatorConfigurationTestOnly.yaml'] }
specsWithOutputRoot.each { specFile, outputRoot, generatorConfigurationFileName ->
    def helper = new Helper(project, technologyStack, outputRoot, nameSeparator, specFile)
    def generateTask = helper.registerOpenApiGenerateTask(technologyStack, "$projectDir/${generatorConfigurationFileName}", [
            artifactVersion         : "${helper.artifactVersion}",
            invokerPackage          : "${helper.namespaceBase}",
            packageName             : "criteo-api-${helper.criteoService}-sdk",
    ]
    )
    generateTask.configure {
        gitUserId = 'criteo'
        gitRepoId = "criteo-api-${helper.criteoService}-${helper.language}-sdk"
    }

    taskList << helper.registerCopyLicenseTask()
    taskList << helper.registerRemoveUnwantedFilesTasks(['.openapi-generator-ignore', '.travis.yml', 'git_push.sh'])
    taskList << generateTask
}

tasks.register("generateClient") {
    group = 'Criteo'
    description = "Generate the ${technologyStack.toUpperCase()} client using openapi-generator and custom templates".toString()
    dependsOn(taskList)
}
