files:
  ClientCredentialsClient.mustache:
    folder : lib
    templateType: SupportingFiles
    destinationFilename: ClientCredentialsClient.php
  ClientCredentialsClientTest.mustache:
    folder : test/Api
    templateType: SupportingFiles
    destinationFilename: ClientCredentialsClientTest.php
  GatewayApiTest.mustache:
    folder : test
    templateType: SupportingFiles
    destinationFilename: GatewayApiTest.php
  ExampleApplication.mustache:
    folder : lib
    templateType: SupportingFiles
    destinationFilename: ExampleApplication.php