files:
  TokenAutoRefreshClient.mustache:
    folder : lib
    templateType: SupportingFiles
    destinationFilename: TokenAutoRefreshClient.php
  TokenAutoRefreshClientTest.mustache:
    folder : test/Api
    templateType: SupportingFiles
    destinationFilename: TokenAutoRefreshClientTest.php