files:
  ClientCredentialsClient.mustache:
    folder : lib
    templateType: SupportingFiles
    destinationFilename: ClientCredentialsClient.php
  ClientCredentialsClientTest.mustache:
    folder : test/Api
    templateType: SupportingFiles
    destinationFilename: ClientCredentialsClientTest.php
  OAuthApiTest.mustache:
    folder : test/Api
    templateType: SupportingFiles
    destinationFilename: OAuthApiTest.php
  GatewayApiTest.mustache:
    folder : test/Api
    templateType: SupportingFiles
    destinationFilename: GatewayApiTest.php