files:
  custom/ClientCredentialsClient.php.mustache:
    folder : lib
    templateType: SupportingFiles
    destinationFilename: ClientCredentialsClient.php
  custom/ClientCredentialsClientTest.php.mustache:
    folder : test/Api
    templateType: SupportingFiles
    destinationFilename: ClientCredentialsClientTest.php
  custom/GatewayApiTest.php.mustache:
    folder : test
    templateType: SupportingFiles
    destinationFilename: GatewayApiTest.php
  custom/ExampleApplication.php.mustache:
    folder : lib
    templateType: SupportingFiles
    destinationFilename: ExampleApplication.php