files:
  custom/ClientCredentialsClient.php.mustache:
    folder : lib
    templateType: SupportingFiles
    destinationFilename: ClientCredentialsClient.php
  custom/ClientCredentialsClientTest.php.mustache:
    folder : test/Api
    templateType: SupportingFiles
    destinationFilename: ClientCredentialsClientTest.php
  custom/OAuthClient.php.mustache:
    folder : lib
    templateType: SupportingFiles
    destinationFilename: OAuthClient.php
  custom/ClientCredentialsClient/Token.php.mustache:
    folder : lib/ClientCredentialsClient
    templateType: SupportingFiles
    destinationFilename: Token.php
  custom/GatewayApiTest.php.mustache:
    folder : test
    templateType: SupportingFiles
    destinationFilename: GatewayApiTest.php
  custom/ExampleApplication.php.mustache:
    folder : lib
    templateType: SupportingFiles
    destinationFilename: ExampleApplication.php