openapi: 3.0.1
info:
  description: Criteo API - MarketingSolutions
  title: Criteo API
  version: Experimental
servers:
- url: https://api.criteo.com
security:
- oauth: []
tags:
- name: Advertiser
- name: Analytics
- name: Audience
- name: Campaign
- name: Catalog
- name: Creative
- name: Gateway
- name: OnSiteRecommendation
- name: Reco
paths:
  /experimental/ads/{ad-id}/product-filter:
    delete:
      description: Disable product filtering for a given ad
      operationId: DisableProductFiltering
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
      summary: "/experimental/ads/{ad-id}/product-filter"
      tags:
      - Reco
      x-accepts: application/json
    get:
      description: Fetch product filtering configuration for a given ad
      operationId: FetchProductFilteringConfig
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
      summary: "/experimental/ads/{ad-id}/product-filter"
      tags:
      - Reco
      x-accepts: application/json
    post:
      description: Enable product filtering for a given ad
      operationId: EnableProductFiltering
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
      summary: "/experimental/ads/{ad-id}/product-filter"
      tags:
      - Reco
      x-content-type: application/json
      x-accepts: application/json
  /experimental/ads/{id}:
    delete:
      description: Delete an Ad
      operationId: DeleteAd
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: "/experimental/ads/{id}"
      tags:
      - Creative
      x-accepts: application/json
    get:
      description: Get an Ad with its id
      operationId: GetAd
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: "/experimental/ads/{id}"
      tags:
      - Creative
      x-accepts: application/json
  /experimental/advertisers/{advertiser-id}/ads:
    get:
      description: Get the list of self-services Ads for a given advertiser
      operationId: GetAdvertiserAds
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: "/experimental/advertisers/{advertiser-id}/ads"
      tags:
      - Creative
      x-accepts: application/json
    post:
      description: Create an Ad
      operationId: CreateAdvertiserAd
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: "/experimental/advertisers/{advertiser-id}/ads"
      tags:
      - Creative
      x-content-type: application/json
      x-accepts: application/json
  /experimental/advertisers/{advertiser-id}/coupons:
    get:
      description: Get the list of self-services Coupons for a given advertiser
      operationId: GetAdvertiserCoupons
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: "/experimental/advertisers/{advertiser-id}/coupons"
      tags:
      - Creative
      x-accepts: application/json
    post:
      description: Create a Coupon
      operationId: CreateAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: "/experimental/advertisers/{advertiser-id}/coupons"
      tags:
      - Creative
      x-content-type: application/json
      x-accepts: application/json
  /experimental/advertisers/{advertiser-id}/coupons-supported-sizes:
    get:
      description: Get the list of Coupon supported sizes
      operationId: GetAdvertiserCouponSupportedSizes
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: "/experimental/advertisers/{advertiser-id}/coupons-supported-sizes"
      tags:
      - Creative
      x-accepts: application/json
  /experimental/advertisers/{advertiser-id}/coupons/{id}:
    delete:
      description: Delete a Coupon
      operationId: DeleteAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: "/experimental/advertisers/{advertiser-id}/coupons/{id}"
      tags:
      - Creative
      x-accepts: application/json
    get:
      description: Get a Coupon with its id
      operationId: GetAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: "/experimental/advertisers/{advertiser-id}/coupons/{id}"
      tags:
      - Creative
      x-accepts: application/json
    put:
      description: Edit a specific Coupon
      operationId: EditAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: "/experimental/advertisers/{advertiser-id}/coupons/{id}"
      tags:
      - Creative
      x-content-type: application/json
      x-accepts: application/json
  /experimental/advertisers/{advertiser-id}/coupons/{id}/preview:
    get:
      description: Get the preview of a specific Coupon
      operationId: GetAdvertiserCouponPreview
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: "/experimental/advertisers/{advertiser-id}/coupons/{id}/preview"
      tags:
      - Creative
      x-accepts: application/json
  /experimental/advertisers/{advertiser-id}/creatives:
    get:
      description: Get the list of self-services Creatives for a given advertiser
      operationId: GetAdvertiserCreatives
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: "/experimental/advertisers/{advertiser-id}/creatives"
      tags:
      - Creative
      x-accepts: application/json
    post:
      description: Create a Creative
      operationId: CreateAdvertiserCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: "/experimental/advertisers/{advertiser-id}/creatives"
      tags:
      - Creative
      x-content-type: application/json
      x-accepts: application/json
  /experimental/advertisers/{advertiser-id}/datasets:
    get:
      description: Retrieves corresponding Datasets for a given Advertiser. Only those
        Datasets are included for which the given Advertiser is marked a primary.
      operationId: ListDatasetsByAdvertiser
      security:
      - oauth: []
      summary: "/experimental/advertisers/{advertiser-id}/datasets"
      tags:
      - Advertiser
      x-accepts: application/json
  /experimental/advertisers/{advertiserId}/targeting/bundle-rules:
    delete:
      description: "Removes some bundles from the current list of targeted bundles\
        \ for a given advertiser.<br />\r\nThe mode of targeting (allowlist/blocklist)\
        \ cannot be updated through this method."
      operationId: DeleteAdvertiserBundleRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/advertisers/{advertiserId}/targeting/bundle-rules"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    get:
      description: Returns a list of all targeted bundles for an advertiser.
      operationId: GetAdvertiserBundleRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: "/experimental/advertisers/{advertiserId}/targeting/bundle-rules"
      tags:
      - Campaign
      x-accepts: application/json
    post:
      description: "Inserts a list of targeted bundles for an advertiser and sets\
        \ the targeting mode : blocklisting or allowlisting.<br />\r\nIt will replace\
        \ the current list if any."
      operationId: PostAdvertiserBundleRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/advertisers/{advertiserId}/targeting/bundle-rules"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    put:
      description: "Updates the targeted bundles for an advertiser by adding a list\
        \ of bundles to the current list.<br />\r\nThe mode of targeting (allowlist/blocklist)\
        \ cannot be updated through this method."
      operationId: PutAdvertiserBundleRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/advertisers/{advertiserId}/targeting/bundle-rules"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/advertisers/{advertiserId}/targeting/domain-rules:
    delete:
      description: "Removes some domains from the current list of targeted domains\
        \ for a given advertiser.<br />\r\nThe mode of targeting (allowlist/blocklist)\
        \ cannot be updated through this method."
      operationId: DeleteAdvertiserDomainRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/advertisers/{advertiserId}/targeting/domain-rules"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    get:
      description: Returns a list of all targeted domains for an advertiser.
      operationId: GetAdvertiserDomainRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: "/experimental/advertisers/{advertiserId}/targeting/domain-rules"
      tags:
      - Campaign
      x-accepts: application/json
    post:
      description: "Inserts a list of targeted domains for an advertiser and sets\
        \ the targeting mode : blocklisting or allowlisting.<br />\r\nIt will replace\
        \ the current list if any."
      operationId: PostAdvertiserDomainRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/advertisers/{advertiserId}/targeting/domain-rules"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    put:
      description: "Updates the targeted domains for an advertiser by adding a list\
        \ of domains to the current list.<br />\r\nThe mode of targeting (allowlist/blocklist)\
        \ cannot be updated through this method."
      operationId: PutAdvertiserDomainRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/advertisers/{advertiserId}/targeting/domain-rules"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/advertisers/me:
    get:
      description: Fetch the portfolio of Advertisers for this account
      operationId: ListAdvertisers
      security:
      - oauth: []
      summary: /experimental/advertisers/me
      tags:
      - Advertiser
      x-accepts: application/json
  /experimental/campaigns/{campaignId}/targeting/bundle-rules:
    delete:
      description: "Removes some bundles from the current list of targeted bundles\
        \ for a given campaign.<br />\r\nThe mode of targeting (allowlist/blocklist)\
        \ cannot be updated through this method."
      operationId: DeleteCampaignBundleRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/campaigns/{campaignId}/targeting/bundle-rules"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    get:
      description: Returns a list of all targeted bundles for a campaign.
      operationId: GetCampaignBundleRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: "/experimental/campaigns/{campaignId}/targeting/bundle-rules"
      tags:
      - Campaign
      x-accepts: application/json
    post:
      description: "Inserts a list of targeted bundles for a campaign and sets the\
        \ targeting mode : blocklisting or allowlisting.<br />\r\nIt will replace\
        \ the current list if any."
      operationId: PostCampaignBundleRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/campaigns/{campaignId}/targeting/bundle-rules"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    put:
      description: "Updates the targeted bundles for a campaign by adding a list of\
        \ bundles to the current list.<br />\r\nThe mode of targeting (allowlist/blocklist)\
        \ cannot be updated through this method."
      operationId: PutCampaignBundleRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/campaigns/{campaignId}/targeting/bundle-rules"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/campaigns/{campaignId}/targeting/domain-rules:
    delete:
      description: "Removes some domains from the current list of targeted domains\
        \ for a given campaign.<br />\r\nThe mode of targeting (allowlist/blocklist)\
        \ cannot be updated through this method."
      operationId: DeleteCampaignDomainRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/campaigns/{campaignId}/targeting/domain-rules"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    get:
      description: Returns a list of all targeted domains for a campaign.
      operationId: GetCampaignDomainRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: "/experimental/campaigns/{campaignId}/targeting/domain-rules"
      tags:
      - Campaign
      x-accepts: application/json
    post:
      description: "Inserts a list of targeted domains for a campaign and sets the\
        \ targeting mode : blocklisting or allowlisting.<br />\r\nIt will replace\
        \ the current list if any."
      operationId: PostCampaignDomainRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/campaigns/{campaignId}/targeting/domain-rules"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    put:
      description: "Updates the targeted domains for a campaign by adding a list of\
        \ domains to the current list.<br />\r\nThe mode of targeting (allowlist/blocklist)\
        \ cannot be updated through this method."
      operationId: PutCampaignDomainRules
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/campaigns/{campaignId}/targeting/domain-rules"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/catalog/products/batch:
    post:
      description: |-
        Used to publish a batch of operations to insert, update and deletes products.
         The batch is processed asynchronously.The response provides an operationToken which can be used to track
         the status of the report of the operation.
      operationId: SubmitCatalogProductsBatch
      security:
      - oauth:
        - MarketingSolutions_Catalog_Manage
      summary: /experimental/catalog/products/batch
      tags:
      - Catalog
      x-content-type: application/json
      x-accepts: application/json
  /experimental/catalog/products/batch/report/{operation-token}:
    get:
      description: Get the report of an asynchronous batch operation previously requested
      operationId: GetCatalogProductsBatchReport
      security:
      - oauth:
        - MarketingSolutions_Catalog_Read
      summary: "/experimental/catalog/products/batch/report/{operation-token}"
      tags:
      - Catalog
      x-accepts: application/json
  /experimental/catalog/stats/merchants/{merchant-id}:
    get:
      description: get an stats request
      operationId: GetCatalogMerchantStats
      security:
      - oauth:
        - MarketingSolutions_Catalog_Read
      summary: "/experimental/catalog/stats/merchants/{merchant-id}"
      tags:
      - Catalog
      x-accepts: application/json
  /experimental/categories/report:
    post:
      description: "With this endpoint you can analyse what are the categories of\
        \ the placements' domains your ads are placed in.\r\n<br/><br/>\r\nThis endpoint\
        \ supports data retrieval for up to three months in the past."
      operationId: GetCategoriesReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: /experimental/categories/report
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/creatives/{id}:
    delete:
      description: Delete a Creative if there are no ads binded to it
      operationId: DeleteCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: "/experimental/creatives/{id}"
      tags:
      - Creative
      x-accepts: application/json
    get:
      description: Get a Creative with its id
      operationId: GetCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: "/experimental/creatives/{id}"
      tags:
      - Creative
      x-accepts: application/json
    put:
      description: Edit a specific Creative
      operationId: EditCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: "/experimental/creatives/{id}"
      tags:
      - Creative
      x-content-type: application/json
      x-accepts: application/json
  /experimental/creatives/{id}/preview:
    post:
      description: Get the preview of a specific Creative
      operationId: GenerateCreativePreview
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: "/experimental/creatives/{id}/preview"
      tags:
      - Creative
      x-accepts: application/json
  /experimental/industries:
    get:
      description: Returns the list of available industries for new advertisers.
      operationId: ListIndustries
      security:
      - oauth: []
      summary: /experimental/industries
      tags:
      - Advertiser
      x-accepts: application/json
  /experimental/log-level/advertisers/{advertiser-id}/report:
    post:
      description: This Statistics endpoint provides publisher data.
      operationId: GetTransparencyReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: "/experimental/log-level/advertisers/{advertiser-id}/report"
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets:
    patch:
      description: Patch a list of AdSets.
      operationId: PatchAdSets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: /experimental/marketing-solutions/ad-sets
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    post:
      description: Create an ad set with the provided parameters
      operationId: CreateAdSet
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: /experimental/marketing-solutions/ad-sets
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets/{ad-set-id}:
    get:
      description: Get the data for the specified ad set
      operationId: GetAdSet
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: "/experimental/marketing-solutions/ad-sets/{ad-set-id}"
      tags:
      - Campaign
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets/{ad-set-id}/audience:
    put:
      description: Link or unlink an audience with an ad set
      operationId: UpdateAdSetAudience
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/marketing-solutions/ad-sets/{ad-set-id}/audience"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets/{ad-set-id}/category-bids:
    get:
      description: Get the Category Bids for all valid Categories associated to an
        Ad Set
      operationId: GetAdSetCategoryBids
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: "/experimental/marketing-solutions/ad-sets/{ad-set-id}/category-bids"
      tags:
      - Campaign
      x-accepts: application/json
    patch:
      description: "Update the Category Bids for given Categories associated to an\
        \ Ad Set\r\nPatch Category Bids for one or more Categories in a single request.\
        \ Partial success policy is followed."
      operationId: PatchAdSetCategoryBids
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/marketing-solutions/ad-sets/{ad-set-id}/category-bids"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets/{ad-set-id}/display-multipliers:
    get:
      description: Get the Display Multipliers for all valid Categories associated
        to an Ad Set
      operationId: GetDisplayMultipliers
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: "/experimental/marketing-solutions/ad-sets/{ad-set-id}/display-multipliers"
      tags:
      - Campaign
      x-accepts: application/json
    patch:
      description: "Update the Display Multipliers for given Categories associated\
        \ to an Ad Set\r\nPatch Display Multipliers for one or more Categories in\
        \ a single request. Partial success policy is followed."
      operationId: PatchDisplayMultipliers
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/marketing-solutions/ad-sets/{ad-set-id}/display-multipliers"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets/{ad-set-id}/targeting/deal-ids:
    get:
      description: Get the Deal Id Targeting configuration for the ad set whose id
        is specified
      operationId: GetAdSetTargetingDealIds
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: "/experimental/marketing-solutions/ad-sets/{ad-set-id}/targeting/deal-ids"
      tags:
      - Campaign
      x-accepts: application/json
    put:
      description: Set the Deal Id Targeting configuration for the ad set whose id
        is specified
      operationId: SetAdSetTargetingDealIds
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/marketing-solutions/ad-sets/{ad-set-id}/targeting/deal-ids"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets/{ad-set-id}/targeting/deal-ids/disable:
    post:
      description: Disable the Deal Id Targeting configuration for the ad set whose
        id is specified
      operationId: DisableAdSetTargetingDealIds
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/marketing-solutions/ad-sets/{ad-set-id}/targeting/deal-ids/disable"
      tags:
      - Campaign
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets/{ad-set-id}/targeting/video-positioning:
    get:
      description: Get the Video Positioning Targeting configuration for the ad set
        whose id is specified
      operationId: GetAdSetTargetingVideoPositioning
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: "/experimental/marketing-solutions/ad-sets/{ad-set-id}/targeting/video-positioning"
      tags:
      - Campaign
      x-accepts: application/json
    put:
      description: Set the Video Positioning Targeting configuration for the ad set
        whose id is specified
      operationId: SetAdSetTargetingVideoPositioning
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/marketing-solutions/ad-sets/{ad-set-id}/targeting/video-positioning"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets/{ad-set-id}/targeting/video-positionings/disable:
    post:
      description: Disable the Video Positioning Targeting configuration for the ad
        set whose id is specified
      operationId: DisableAdSetTargetingVideoPositioning
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: "/experimental/marketing-solutions/ad-sets/{ad-set-id}/targeting/video-positionings/disable"
      tags:
      - Campaign
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets/search:
    post:
      description: "Search for ad sets based on provided criteria.\r\nThis returns\
        \ the full configuration of ad sets matching those criteria.\r\nField projection\
        \ can be used if only a subset of fields is required, instead of the full\
        \ configuration.\r\n            \r\nIf specific fields are precised in the\
        \ user prompt, use meta.fields field projection in order to query only the\
        \ value of these fields, else, provide every field."
      operationId: SearchAdSets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: /experimental/marketing-solutions/ad-sets/search
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets/start:
    post:
      description: Start the specified list of ad sets
      operationId: StartAdSets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: /experimental/marketing-solutions/ad-sets/start
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets/stop:
    post:
      description: Stop the specified list of ad sets
      operationId: StopAdSets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: /experimental/marketing-solutions/ad-sets/stop
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/ad-sets/targeting/supply-vendors:
    get:
      description: Fetch the list of available supply vendors for any Ad Set targetings
      operationId: GetSupplyVendorList
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: /experimental/marketing-solutions/ad-sets/targeting/supply-vendors
      tags:
      - Campaign
      x-accepts: application/json
  /experimental/marketing-solutions/ads/{ad-id}/audience-segment:
    delete:
      description: Delete the link between an Ad and an Audience Segment.
      operationId: DeleteAdSegmentLink
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: "/experimental/marketing-solutions/ads/{ad-id}/audience-segment"
      tags:
      - Creative
      x-accepts: application/json
    get:
      description: Retrieve the Ad audience segment link.
      operationId: GetAdSegmentLink
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: "/experimental/marketing-solutions/ads/{ad-id}/audience-segment"
      tags:
      - Creative
      x-accepts: application/json
    put:
      description: "Link an Ad with an Audience Segment. If a link already exists,\
        \ its segment ID will be updated."
      operationId: LinkAdSegment
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: "/experimental/marketing-solutions/ads/{ad-id}/audience-segment"
      tags:
      - Creative
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/ads/{ad-id}/product-boost:
    get:
      description: Fetch all boosting associations and configurations
      operationId: FetchBoostedAdAssociations
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
      summary: "/experimental/marketing-solutions/ads/{ad-id}/product-boost"
      tags:
      - Reco
      x-accepts: application/json
  /experimental/marketing-solutions/ads/{ad-id}/product-boost/{product-set-id}:
    delete:
      description: Delete association and configuration.
      operationId: DeleteBoostedAdAssociation
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
      summary: "/experimental/marketing-solutions/ads/{ad-id}/product-boost/{product-set-id}"
      tags:
      - Reco
      x-accepts: application/json
    get:
      description: Fetch boosting association and configuration
      operationId: FetchBoostedAdAssociation
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
      summary: "/experimental/marketing-solutions/ads/{ad-id}/product-boost/{product-set-id}"
      tags:
      - Reco
      x-accepts: application/json
    post:
      description: Create or update product boosting configuration
      operationId: CreateBoostedAdAssociation
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
      summary: "/experimental/marketing-solutions/ads/{ad-id}/product-boost/{product-set-id}"
      tags:
      - Reco
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audience-segments:
    patch:
      description: "Updates the properties of all segments with a valid configuration,\
        \ and returns their IDs. For those that cannot be updated, one or multiple\
        \ errors are returned."
      operationId: UpdateAudienceSegments
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: /experimental/marketing-solutions/audience-segments
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audience-segments/{audience-segment-id}/contact-list:
    delete:
      description: Delete all identifiers from a contact list audience-segment.
      operationId: DeleteContactListByAudienceSegment
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: "/experimental/marketing-solutions/audience-segments/{audience-segment-id}/contact-list"
      tags:
      - Audience
      x-accepts: application/json
    patch:
      description: Add/remove identifiers to or from a contact list audience-segment.
      operationId: UpdateContactListByAudienceSegment
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: "/experimental/marketing-solutions/audience-segments/{audience-segment-id}/contact-list"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audience-segments/{audience-segment-id}/contact-list/statistics:
    get:
      description: Returns the statistics of a contact list segment.
      operationId: GetAudienceSegmentContactListStatistics
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      summary: "/experimental/marketing-solutions/audience-segments/{audience-segment-id}/contact-list/statistics"
      tags:
      - Audience
      x-accepts: application/json
  /experimental/marketing-solutions/audience-segments/compute-sizes:
    post:
      description: Gets the size of all segments. An error is returned for those whose
        size calculation is not supported.
      operationId: ComputeAudienceSegmentsSizes
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: /experimental/marketing-solutions/audience-segments/compute-sizes
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audience-segments/create:
    post:
      description: "Creates all segments with a valid configuration, and returns their\
        \ IDs. For those that cannot be created, one or multiple errors are returned."
      operationId: CreateAudienceSegments
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: /experimental/marketing-solutions/audience-segments/create
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audience-segments/delete:
    post:
      description: Delete the segments associated to the given audience IDs.
      operationId: DeleteAudienceSegments
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: /experimental/marketing-solutions/audience-segments/delete
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audience-segments/estimate-size:
    post:
      description: Gets the size estimation of a non existent segment. An error is
        returned when size calculation is not supported.
      operationId: EstimateAudienceSegmentsSizes
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: /experimental/marketing-solutions/audience-segments/estimate-size
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audience-segments/in-market-brands:
    get:
      description: Returns a list with all available in-market brands that can be
        used to define an in-market segment.
      operationId: GetAudienceSegmentsInMarketBrands
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      summary: /experimental/marketing-solutions/audience-segments/in-market-brands
      tags:
      - Audience
      x-accepts: application/json
  /experimental/marketing-solutions/audience-segments/in-market-interests:
    get:
      description: Returns a list with all available in-market interests that can
        be used to define an in-market segment. These in-market interests correspond
        to the Google product taxonomy.
      operationId: GetAudienceSegmentsInMarketInterests
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      summary: /experimental/marketing-solutions/audience-segments/in-market-interests
      tags:
      - Audience
      x-accepts: application/json
  /experimental/marketing-solutions/audience-segments/search:
    post:
      description: "Returns a list of segments that match the provided filters. If\
        \ present, the filters are AND'ed together when applied."
      operationId: SearchAudienceSegments
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      summary: /experimental/marketing-solutions/audience-segments/search
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audiences:
    patch:
      description: "Updates the properties of all audiences with a valid configuration,\
        \ and returns their IDs. For those that cannot be updated, one or multiple\
        \ errors are returned."
      operationId: UpdateAudiences
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: /experimental/marketing-solutions/audiences
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audiences/{audience-id}/contactlist-attributes:
    patch:
      description: Add/remove identifiers to or from a contact list.
      operationId: ModifyAudienceUsersWithAttributes
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: "/experimental/marketing-solutions/audiences/{audience-id}/contactlist-attributes"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audiences/compute-sizes:
    post:
      description: Gets the size of all audiences. An error is returned for those
        whose size calculation is not supported.
      operationId: ComputeAudiencesSizes
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: /experimental/marketing-solutions/audiences/compute-sizes
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audiences/create:
    post:
      description: "Creates all audiences with a valid configuration, and returns\
        \ their IDs. For those that cannot be created, one or multiple errors are\
        \ returned."
      operationId: CreateAudiences
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: /experimental/marketing-solutions/audiences/create
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audiences/delete:
    post:
      description: Deletes the audiences associated to the given audience IDs.
      operationId: DeleteAudiences
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: /experimental/marketing-solutions/audiences/delete
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audiences/estimate-size:
    post:
      description: Gets the size estimation of a non existent audience. An error is
        returned when size calculation is not supported.
      operationId: EstimateAudiencesSizes
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: /experimental/marketing-solutions/audiences/estimate-size
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/audiences/search:
    post:
      description: "Returns a list of audiences that match the provided filters. If\
        \ present, the filters are AND'ed together when applied."
      operationId: SearchAudiences
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      summary: /experimental/marketing-solutions/audiences/search
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/campaigns:
    patch:
      description: "Patch a list of Campaigns.\r\n            \r\nA campaign, or in\
        \ other words a marketing campaign, is an entity that defines advertising\
        \ objectives and success criteria."
      operationId: PatchCampaigns
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: /experimental/marketing-solutions/campaigns
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    post:
      description: "Create the specified campaign\r\n            \r\nA campaign, or\
        \ in other words a marketing campaign, is an entity that defines advertising\
        \ objectives and success criteria."
      operationId: CreateCampaign
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: /experimental/marketing-solutions/campaigns
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/campaigns/{campaign-id}:
    get:
      description: "Get the data for the specified campaign.\r\n            \r\nA\
        \ campaign, or in other words a marketing campaign, is an entity that defines\
        \ advertising objectives and success criteria."
      operationId: GetCampaign
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: "/experimental/marketing-solutions/campaigns/{campaign-id}"
      tags:
      - Campaign
      x-accepts: application/json
  /experimental/marketing-solutions/campaigns/search:
    post:
      description: "Search endpoint for campaigns\r\n            \r\nA campaign, or\
        \ in other words a marketing campaign, is an entity that defines advertising\
        \ objectives and success criteria."
      operationId: SearchCampaigns
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: /experimental/marketing-solutions/campaigns/search
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/dataset/{dataset-id}/product-boost:
    get:
      description: Fetch boosting association and configuration for a given partner
      operationId: FetchBoostedAdAssociationByPartnerId
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
      summary: "/experimental/marketing-solutions/dataset/{dataset-id}/product-boost"
      tags:
      - Reco
      x-accepts: application/json
  /experimental/marketing-solutions/marketplace-performance-outcomes/stats/realtime-reports/{reportId}:
    get:
      description: "Downloads the generated marketplace performance outcomes realtime\
        \ report export.\r\n<br />\r\nThis endpoint is subject to specific rate limits."
      operationId: GetRealtimeProduct
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: "/experimental/marketing-solutions/marketplace-performance-outcomes/stats/realtime-reports/{reportId}"
      tags:
      - Analytics
      x-accepts: application/json
  /experimental/marketing-solutions/marketplace-performance-outcomes/stats/realtime-reports/export:
    post:
      description: "Creates a marketplace performance outcomes realtime report export.\r\
        \n<br />\r\nThis endpoint is subject to specific rate limits."
      operationId: CreateRealtimeProductReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: /experimental/marketing-solutions/marketplace-performance-outcomes/stats/realtime-reports/export
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/marketing-solutions/marketplace-performance-outcomes/stats/report-jobs/{reportId}:
    get:
      description: Gets the status of  report export job.
      operationId: GetMarketplacePerformanceOutcomesExportStatus
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: "/experimental/marketing-solutions/marketplace-performance-outcomes/stats/report-jobs/{reportId}"
      tags:
      - Analytics
      x-accepts: application/json
  /experimental/marketing-solutions/me:
    get:
      description: Get information about the currently logged application
      operationId: GetCurrentApplication
      security:
      - oauth: []
      summary: /experimental/marketing-solutions/me
      tags:
      - Gateway
      x-accepts: application/json
  /experimental/marketing-solutions/report-jobs/{reportId}:
    get:
      description: Gets the status of  report export job.
      operationId: GetExportStatus
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: "/experimental/marketing-solutions/report-jobs/{reportId}"
      tags:
      - Analytics
      x-accepts: application/json
  /experimental/marketing-solutions/report/products/{reportId}:
    get:
      description: "Downloads the generated all-products report export.\r\n<br />\r\
        \nThis endpoint is subject to specific rate limits."
      operationId: DownloadAllProductsExport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: "/experimental/marketing-solutions/report/products/{reportId}"
      tags:
      - Analytics
      x-accepts: application/json
  /experimental/marketing-solutions/report/products/export:
    post:
      description: "Creates an all-products report export job.\r\n<br />\r\nThis endpoint\
        \ is subject to specific rate limits."
      operationId: CreateAllProductsExport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: /experimental/marketing-solutions/report/products/export
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/placements/report:
    post:
      description: "Your ads are placed in different domains (publishers) and environments\
        \ (websites and apps). Thanks to the placements endpoint, you can analyse\
        \ the performances for each publisher, comparing displays, clicks and sales\
        \ generated.\r\n<br/><br/>\r\nThis endpoint supports data retrieval for up\
        \ to three months in the past."
      operationId: GetPlacementsReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: /experimental/placements/report
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/product-sets:
    post:
      description: Create a new product set
      operationId: CreateProductSet
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
      summary: /experimental/product-sets
      tags:
      - Reco
      x-content-type: application/json
      x-accepts: application/json
  /experimental/product-sets/{product-set-id}:
    delete:
      description: Remove a product set
      operationId: RemoveProductSet
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
      summary: "/experimental/product-sets/{product-set-id}"
      tags:
      - Reco
      x-accepts: application/json
    get:
      description: Fetch an existing product set
      operationId: FetchProductSet
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
      summary: "/experimental/product-sets/{product-set-id}"
      tags:
      - Reco
      x-accepts: application/json
    patch:
      description: Patch an existing product set
      operationId: PatchProductSet
      security:
      - oauth:
        - MarketingSolutions_Reco_Manage
      summary: "/experimental/product-sets/{product-set-id}"
      tags:
      - Reco
      x-content-type: application/json
      x-accepts: application/json
  /experimental/product-sets/{product-set-id}/product-filters:
    get:
      description: Fetch product filtering usages for a given product set
      operationId: FetchProductFilteringUsages
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
      summary: "/experimental/product-sets/{product-set-id}/product-filters"
      tags:
      - Reco
      x-accepts: application/json
  /experimental/product-sets/dataset/{dataset-id}:
    get:
      description: Fetch product sets of a given dataset
      operationId: FetchProductSets
      security:
      - oauth:
        - MarketingSolutions_Reco_Read
      summary: "/experimental/product-sets/dataset/{dataset-id}"
      tags:
      - Reco
      x-accepts: application/json
  /experimental/recommendation/search:
    post:
      description: "Retrieves a list of products recommended for the given user. This\
        \ end point can either rely on a Criteo UserId, or a list of user events to\
        \ perform the recommendation"
      operationId: SearchRecommendedProducts
      security:
      - oauth:
        - MarketingSolutions_OnSiteRecommendation_Read
      summary: /experimental/recommendation/search
      tags:
      - OnSiteRecommendation
      x-content-type: application/json
      x-accepts: application/json
  /experimental/recommendation/search-conversational:
    post:
      description: Retrieves a list of products recommended for the given user based
        on a conversation between a user and a partner's agent
      operationId: SearchRecommendedProductsConversational
      security:
      - oauth:
        - MarketingSolutions_OnSiteRecommendation_Read
      summary: /experimental/recommendation/search-conversational
      tags:
      - OnSiteRecommendation
      x-content-type: application/json
      x-accepts: application/json
  /experimental/reports/{report-id}/output:
    get:
      description: This endpoint gives you the output of the report.
      operationId: GetAsyncExportOutput
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: "/experimental/reports/{report-id}/output"
      tags:
      - Analytics
      x-accepts: application/json
  /experimental/reports/{report-id}/status:
    get:
      description: This endpoint gives you the status of the report.
      operationId: GetAsyncExportStatus
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: "/experimental/reports/{report-id}/status"
      tags:
      - Analytics
      x-accepts: application/json
  /experimental/reports/async-audience-performance:
    post:
      description: This Statistics endpoint provides an export Id that lets you retrieve
        data.
      operationId: GetAsyncAudienceReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: /experimental/reports/async-audience-performance
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/reports/async-statistics:
    post:
      description: This Statistics endpoint provides an export Id that let you retrieve
        data.
      operationId: GetAsyncAdsetReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: /experimental/reports/async-statistics
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/reports/creatives:
    post:
      description: "With Creatives endpoint, you can analyse the daily performances\
        \ of your creatives on the main metrics: clicks, ctr, displays.\r\n<br/><br/>\r\
        \nThis endpoint supports data retrieval for up to two years in the past."
      operationId: GetCreativesReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: /experimental/reports/creatives
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/reports/realtime:
    post:
      description: "With Realtime endpoint, you can analyse the realtime values of\
        \ the main metrics: displays, clicks, cost."
      operationId: GetRealtimeStatisticsReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: /experimental/reports/realtime
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/reports/top-products:
    post:
      description: "With the topProducts endpoint, you can analyse the performances\
        \ for each publisher, by top displays, top clicks or top sales.\r\n<br/><br/>\r\
        \nThis endpoint supports data retrieval for up to one year in the past."
      operationId: GetTopProductsReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: /experimental/reports/top-products
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/statistics/report:
    post:
      description: "This Statistics endpoint provides ad set related data. It is an\
        \ upgrade of our previous Statistics endpoint, and includes new metrics and\
        \ customization capabilities.\r\n<br/><br/>\r\nThis endpoint supports data\
        \ retrieval for up to two years in the past."
      operationId: GetAdsetReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: /experimental/statistics/report
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/transactions/report:
    post:
      description: "This Transactions endpoint provides transactions id related data.\r\
        \n<br/><br/>\r\nThis endpoint supports data retrieval for up to two years\
        \ in the past."
      operationId: GetTransactionsReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: /experimental/transactions/report
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
components:
  securitySchemes:
    oauth:
      flows:
        authorizationCode:
          authorizationUrl: https://api.criteo.com/oauth2
          scopes: {}
          tokenUrl: https://api.criteo.com/oauth2/token
        clientCredentials:
          scopes: {}
          tokenUrl: https://api.criteo.com/oauth2/token
      type: oauth2
x-samples-languages:
- java
- python
- php
- csharp
- javascript
- curl
- ruby

