{
  "openapi": "3.0.1",
  "info": {
    "title": "Criteo API",
    "description": "Criteo API - MarketingSolutions",
    "version": "Preview"
  },
  "servers": [
    {
      "url": "https://api.criteo.com"
    }
  ],
  "paths": {
    "/preview/ads/{ad-id}/product-filter": {
      "delete": {
        "tags": [
          "Reco"
        ],
        "description": "Disable product filtering for a given ad",
        "operationId": "DisableProductFiltering",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Reco_Manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Reco"
        ],
        "description": "Fetch product filtering configuration for a given ad",
        "operationId": "FetchProductFilteringConfig",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Reco_Read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Reco"
        ],
        "description": "Enable product filtering for a given ad",
        "operationId": "EnableProductFiltering",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Reco_Manage"
            ]
          }
        ]
      }
    },
    "/preview/ads/{id}": {
      "delete": {
        "tags": [
          "Creative"
        ],
        "description": "Delete an Ad",
        "operationId": "DeleteAd",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Creative"
        ],
        "description": "Get an Ad with its id",
        "operationId": "GetAd",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Read"
            ]
          }
        ]
      }
    },
    "/preview/advertisers/{advertiser-id}/ads": {
      "get": {
        "tags": [
          "Creative"
        ],
        "description": "Get the list of self-services Ads for a given advertiser",
        "operationId": "GetAdvertiserAds",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Creative"
        ],
        "description": "Create an Ad",
        "operationId": "CreateAdvertiserAd",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Manage"
            ]
          }
        ]
      }
    },
    "/preview/advertisers/{advertiser-id}/coupons": {
      "get": {
        "tags": [
          "Creative"
        ],
        "description": "Get the list of self-services Coupons for a given advertiser",
        "operationId": "GetAdvertiserCoupons",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Creative"
        ],
        "description": "Create a Coupon",
        "operationId": "CreateAdvertiserCoupon",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Manage"
            ]
          }
        ]
      }
    },
    "/preview/advertisers/{advertiser-id}/coupons-supported-sizes": {
      "get": {
        "tags": [
          "Creative"
        ],
        "description": "Get the list of Coupon supported sizes",
        "operationId": "GetAdvertiserCouponSupportedSizes",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Read"
            ]
          }
        ]
      }
    },
    "/preview/advertisers/{advertiser-id}/coupons/{id}": {
      "delete": {
        "tags": [
          "Creative"
        ],
        "description": "Delete a Coupon",
        "operationId": "DeleteAdvertiserCoupon",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Creative"
        ],
        "description": "Get a Coupon with its id",
        "operationId": "GetAdvertiserCoupon",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Creative"
        ],
        "description": "Edit a specific Coupon",
        "operationId": "EditAdvertiserCoupon",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Manage"
            ]
          }
        ]
      }
    },
    "/preview/advertisers/{advertiser-id}/coupons/{id}/preview": {
      "get": {
        "tags": [
          "Creative"
        ],
        "description": "Get the preview of a specific Coupon",
        "operationId": "GetAdvertiserCouponPreview",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Read"
            ]
          }
        ]
      }
    },
    "/preview/advertisers/{advertiser-id}/creatives": {
      "get": {
        "tags": [
          "Creative"
        ],
        "description": "Get the list of self-services Creatives for a given advertiser",
        "operationId": "GetAdvertiserCreatives",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Creative"
        ],
        "description": "Create a Creative",
        "operationId": "CreateAdvertiserCreative",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Manage"
            ]
          }
        ]
      }
    },
    "/preview/advertisers/{advertiser-id}/datasets": {
      "get": {
        "tags": [
          "Advertiser"
        ],
        "description": "Retrieves corresponding Datasets for a given Advertiser. Only those Datasets are included for which the given Advertiser is marked a primary.",
        "operationId": "getDatasetList",
        "security": [
          {
            "oauth": [ ]
          }
        ]
      }
    },
    "/preview/advertisers/{advertiserId}/targeting/bundle-rules": {
      "delete": {
        "tags": [
          "Campaign"
        ],
        "description": "Removes some bundles from the current list of targeted bundles for a given advertiser.<br />\r\nThe mode of targeting (allowlist/blocklist) cannot be updated through this method.",
        "operationId": "DeleteAdvertiserBundleRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Returns a list of all targeted bundles for an advertiser.",
        "operationId": "GetAdvertiserBundleRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Inserts a list of targeted bundles for an advertiser and sets the targeting mode : blocklisting or allowlisting.<br />\r\nIt will replace the current list if any.",
        "operationId": "PostAdvertiserBundleRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "description": "Updates the targeted bundles for an advertiser by adding a list of bundles to the current list.<br />\r\nThe mode of targeting (allowlist/blocklist) cannot be updated through this method.",
        "operationId": "PutAdvertiserBundleRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/advertisers/{advertiserId}/targeting/domain-rules": {
      "delete": {
        "tags": [
          "Campaign"
        ],
        "description": "Removes some domains from the current list of targeted domains for a given advertiser.<br />\r\nThe mode of targeting (allowlist/blocklist) cannot be updated through this method.",
        "operationId": "DeleteAdvertiserDomainRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Returns a list of all targeted domains for an advertiser.",
        "operationId": "GetAdvertiserDomainRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Inserts a list of targeted domains for an advertiser and sets the targeting mode : blocklisting or allowlisting.<br />\r\nIt will replace the current list if any.",
        "operationId": "PostAdvertiserDomainRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "description": "Updates the targeted domains for an advertiser by adding a list of domains to the current list.<br />\r\nThe mode of targeting (allowlist/blocklist) cannot be updated through this method.",
        "operationId": "PutAdvertiserDomainRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/advertisers/me": {
      "get": {
        "tags": [
          "Advertiser"
        ],
        "description": "Fetch the portfolio of Advertisers for this account",
        "operationId": "ApiPortfolioGet",
        "security": [
          {
            "oauth": [ ]
          }
        ]
      }
    },
    "/preview/audiences/{audience-id}/contactlist-attributes": {
      "patch": {
        "tags": [
          "Audience"
        ],
        "description": "Add/remove identifiers to or from a contact list.",
        "operationId": "modifyAudienceUsersWithAttributes",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/campaigns/{campaignId}/targeting/bundle-rules": {
      "delete": {
        "tags": [
          "Campaign"
        ],
        "description": "Removes some bundles from the current list of targeted bundles for a given campaign.<br />\r\nThe mode of targeting (allowlist/blocklist) cannot be updated through this method.",
        "operationId": "DeleteCampaignBundleRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Returns a list of all targeted bundles for a campaign.",
        "operationId": "GetCampaignBundleRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Inserts a list of targeted bundles for a campaign and sets the targeting mode : blocklisting or allowlisting.<br />\r\nIt will replace the current list if any.",
        "operationId": "PostCampaignBundleRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "description": "Updates the targeted bundles for a campaign by adding a list of bundles to the current list.<br />\r\nThe mode of targeting (allowlist/blocklist) cannot be updated through this method.",
        "operationId": "PutCampaignBundleRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/campaigns/{campaignId}/targeting/domain-rules": {
      "delete": {
        "tags": [
          "Campaign"
        ],
        "description": "Removes some domains from the current list of targeted domains for a given campaign.<br />\r\nThe mode of targeting (allowlist/blocklist) cannot be updated through this method.",
        "operationId": "DeleteCampaignDomainRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Returns a list of all targeted domains for a campaign.",
        "operationId": "GetCampaignDomainRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Inserts a list of targeted domains for a campaign and sets the targeting mode : blocklisting or allowlisting.<br />\r\nIt will replace the current list if any.",
        "operationId": "PostCampaignDomainRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "description": "Updates the targeted domains for a campaign by adding a list of domains to the current list.<br />\r\nThe mode of targeting (allowlist/blocklist) cannot be updated through this method.",
        "operationId": "PutCampaignDomainRules",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/catalog/products/batch": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "description": "Used to publish a batch of operations to insert, update and deletes products.\n The batch is processed asynchronously.The response provides an operationToken which can be used to track\n the status of the report of the operation.",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Catalog_Manage"
            ]
          }
        ]
      }
    },
    "/preview/catalog/products/batch/report/{operation-token}": {
      "get": {
        "tags": [
          "Catalog"
        ],
        "description": "Get the report of an asynchronous batch operation previously requested",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Catalog_Read"
            ]
          }
        ]
      }
    },
    "/preview/catalog/stats/merchants/{merchant-id}": {
      "get": {
        "tags": [
          "Catalog"
        ],
        "description": "get an stats request",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Catalog_Read"
            ]
          }
        ]
      }
    },
    "/preview/categories/report": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "With this endpoint you can analyse what are the categories of the placements' domains your ads are placed in.",
        "operationId": "GetCategoriesReport",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/creatives/{id}": {
      "delete": {
        "tags": [
          "Creative"
        ],
        "description": "Delete a Creative if there are no ads binded to it",
        "operationId": "DeleteCreative",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Creative"
        ],
        "description": "Get a Creative with its id",
        "operationId": "GetCreative",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Creative"
        ],
        "description": "Edit a specific Creative",
        "operationId": "EditCreative",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Manage"
            ]
          }
        ]
      }
    },
    "/preview/creatives/{id}/preview": {
      "post": {
        "tags": [
          "Creative"
        ],
        "description": "Get the preview of a specific Creative",
        "operationId": "GenerateCreativePreview",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Creative_Manage"
            ]
          }
        ]
      }
    },
    "/preview/industries": {
      "get": {
        "tags": [
          "Advertiser"
        ],
        "description": "Returns the list of available industries for new advertisers.",
        "operationId": "listIndustries",
        "security": [
          {
            "oauth": [ ]
          }
        ]
      }
    },
    "/preview/log-level/advertisers/{advertiser-id}/report": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "This Statistics endpoint provides publisher data.",
        "operationId": "GetTransparencyReport",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets": {
      "patch": {
        "tags": [
          "Campaign"
        ],
        "description": "Patch a list of AdSets.",
        "operationId": "PatchAdSetsV24Q3",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Create the specified ad set",
        "operationId": "CreateAdSetV24Q3",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets/{ad-set-id}": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Get the data for the specified ad set",
        "operationId": "GetAdSetV24Q3",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets/{ad-set-id}/audience": {
      "put": {
        "tags": [
          "Campaign"
        ],
        "description": "Link or unlink an audience with an ad set",
        "operationId": "updateAdSetAudience",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets/{ad-set-id}/category-bids": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Get the Category Bids for all valid Categories associated to an Ad Set",
        "operationId": "GetCategoryBidList",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Campaign"
        ],
        "description": "Patch Category Bids for one or more Categories in a single request. Partial success policy is followed.",
        "operationId": "PatchCategoryBidList",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets/{ad-set-id}/display-multipliers": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Get the Display Multipliers for all valid Categories associated to an Ad Set",
        "operationId": "GetDisplayMultipliers",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Campaign"
        ],
        "description": "Patch Display Multipliers for one or more Categories in a single request. Partial success policy is followed.",
        "operationId": "PatchDisplayMultipliers",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets/{ad-set-id}/targeting/deal-ids": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Get the Deal Id Targeting configuration for the ad set whose id is specified",
        "operationId": "GetAdSetTargetingDealIds",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "description": "Set the Deal Id Targeting configuration for the ad set whose id is specified",
        "operationId": "SetAdSetTargetingDealIds",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets/{ad-set-id}/targeting/deal-ids/disable": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Disable the Deal Id Targeting configuration for the ad set whose id is specified",
        "operationId": "DisableAdSetTargetingDealIds",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets/{ad-set-id}/targeting/video-positioning": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Get the Video Positioning Targeting configuration for the ad set whose id is specified",
        "operationId": "GetAdSetTargetingVideoPositioning",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "description": "Set the Video Positioning Targeting configuration for the ad set whose id is specified",
        "operationId": "SetAdSetTargetingVideoPositioning",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets/{ad-set-id}/targeting/video-positionings/disable": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Disable the Video Positioning Targeting configuration for the ad set whose id is specified",
        "operationId": "DisableAdSetTargetingVideoPositioning",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets/search": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Search for ad sets",
        "operationId": "SearchAdSetsV24Q3",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets/start": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Start the specified list of ad sets",
        "operationId": "StartAdSets",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets/stop": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Stop the specified list of ad sets",
        "operationId": "StopAdSets",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/ad-sets/targeting/supply-vendors": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Fetch the list of available supply vendors for any Ad Set targetings",
        "operationId": "GetSupplyVendorList",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audience-segments": {
      "patch": {
        "tags": [
          "Audience"
        ],
        "description": "Updates the properties of all segments with a valid configuration, and returns their IDs. For those that cannot be updated, one or multiple errors are returned.",
        "operationId": "bulkUpdateAudienceSegments",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audience-segments/{audience-segment-id}/contact-list": {
      "delete": {
        "tags": [
          "Audience"
        ],
        "description": "Delete all identifiers from a contact list audience-segment.",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Audience"
        ],
        "description": "Add/remove identifiers to or from a contact list audience-segment.",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Audience"
        ],
        "description": "Returns the statistics of a contact list segment.",
        "operationId": "getAudienceSegmentContactListStatistics",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Read"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audience-segments/compute-sizes": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Gets the size of all segments. An error is returned for those whose size calculation is not supported.",
        "operationId": "computeAudienceSegmentsSizes",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audience-segments/create": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Creates all segments with a valid configuration, and returns their IDs. For those that cannot be created, one or multiple errors are returned.",
        "operationId": "bulkCreateAudienceSegments",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audience-segments/delete": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Delete the segments associated to the given audience IDs.",
        "operationId": "bulkDeleteAudienceSegments",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audience-segments/estimate-size": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Gets the size estimation of a non existent segment. An error is returned when size calculation is not supported.",
        "operationId": "estimateAudienceSegmentSize",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audience-segments/in-market-brands": {
      "get": {
        "tags": [
          "Audience"
        ],
        "description": "Returns a list with all available in-market brands that can be used to define an in-market segment.",
        "operationId": "getAudienceSegmentsInMarketBrands",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Read"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audience-segments/in-market-interests": {
      "get": {
        "tags": [
          "Audience"
        ],
        "description": "Returns a list with all available in-market interests that can be used to define an in-market segment. These in-market interests correspond to the Google product taxonomy.",
        "operationId": "getAudienceSegmentsInMarketInterests",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Read"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audience-segments/search": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Returns a list of segments that match the provided filters. If present, the filters are AND'ed together when applied.",
        "operationId": "searchAudienceSegments",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Read"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audiences": {
      "patch": {
        "tags": [
          "Audience"
        ],
        "description": "Updates the properties of all audiences with a valid configuration, and returns their IDs. For those that cannot be updated, one or multiple errors are returned.",
        "operationId": "bulkUpdateAudiences",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audiences/compute-sizes": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Gets the size of all audiences. An error is returned for those whose size calculation is not supported.",
        "operationId": "computeAudiencesSizes",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audiences/create": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Creates all audiences with a valid configuration, and returns their IDs. For those that cannot be created, one or multiple errors are returned.",
        "operationId": "bulkCreateAudiences",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audiences/delete": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Deletes the audiences associated to the given audience IDs.",
        "operationId": "bulkDeleteAudiences",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audiences/estimate-size": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Gets the size estimation of a non existent audience. An error is returned when size calculation is not supported.",
        "operationId": "estimateAudienceSize",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/audiences/search": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Returns a list of audiences that match the provided filters. If present, the filters are AND'ed together when applied.",
        "operationId": "searchAudiences",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Audience_Read"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/campaigns": {
      "patch": {
        "tags": [
          "Campaign"
        ],
        "description": "Patch a list of Campaigns.",
        "operationId": "PatchCampaigns",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Create the specified campaign",
        "operationId": "CreateCampaign",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/campaigns/{campaign-id}": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Get the data for the specified campaign",
        "operationId": "GetCampaignV23Q1",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/campaigns/search": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Search for campaigns",
        "operationId": "SearchCampaignsV23Q1",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/marketing-solutions/me": {
      "get": {
        "tags": [
          "Gateway"
        ],
        "description": "Get information about the currently logged application",
        "operationId": "GetCurrentApplication",
        "security": [
          {
            "oauth": [ ]
          }
        ]
      }
    },
    "/preview/placements/report": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "Your ads are placed in different domains (publishers) and environments (websites and apps). Thanks to the placements endpoint, you can analyse the performances for each publisher, comparing displays, clicks and sales generated.",
        "operationId": "GetPlacementsReport",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/product-sets": {
      "post": {
        "tags": [
          "Reco"
        ],
        "description": "Create a new product set",
        "operationId": "CreateProductSet",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Reco_Manage"
            ]
          }
        ]
      }
    },
    "/preview/product-sets/{product-set-id}": {
      "delete": {
        "tags": [
          "Reco"
        ],
        "description": "Remove a product set",
        "operationId": "RemoveProductSet",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Reco_Manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Reco"
        ],
        "description": "Fetch an existing product set",
        "operationId": "FetchProductSet",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Reco_Read"
            ]
          }
        ]
      }
    },
    "/preview/product-sets/{product-set-id}/product-filters": {
      "get": {
        "tags": [
          "Reco"
        ],
        "description": "Fetch product filtering usages for a given product set",
        "operationId": "FetchProductFilteringUsages",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Reco_Read"
            ]
          }
        ]
      }
    },
    "/preview/product-sets/dataset/{dataset-id}": {
      "get": {
        "tags": [
          "Reco"
        ],
        "description": "Fetch product sets of a given dataset",
        "operationId": "FetchProductSets",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Reco_Read"
            ]
          }
        ]
      }
    },
    "/preview/recommendation/search": {
      "post": {
        "tags": [
          "OnSiteRecommendation"
        ],
        "description": "Retrieves a list of products recommended for the given user. This end point can either rely on a Criteo UserId, or a list of user events to perform the recommendation.",
        "operationId": "ApiV1RecoPost",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_OnSiteRecommendation_Read"
            ]
          }
        ]
      }
    },
    "/preview/reports/{report-id}/output": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "description": "This endpoint gives you the output of the report.",
        "operationId": "GetAsyncExportOutput",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/reports/{report-id}/status": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "description": "This endpoint gives you the status of the report.",
        "operationId": "GetAsyncExportStatus",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/reports/async-audience-performance": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "This Statistics endpoint provides an export Id that lets you retrieve data.",
        "operationId": "GetAsyncAudienceReport",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/reports/async-statistics": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "This Statistics endpoint provides an export Id that let you retrieve data.",
        "operationId": "GetAsyncAdsetReport",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/reports/creatives": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "With Creatives endpoint, you can analyse the daily performances of your creatives on the main metrics: clicks, ctr, displays.",
        "operationId": "GetCreativesReport",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/reports/realtime": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "With Realtime endpoint, you can analyse the realtime values of the main metrics: displays, clicks, cost.",
        "operationId": "GetRealtimeStatisticsReport",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/reports/top-products": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "With the topProducts endpoint, you can analyse the performances for each publisher, by top displays, top clicks or top sales.",
        "operationId": "GetTopProductsReport",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/statistics/report": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "This Statistics endpoint provides adset related data. It is an upgrade of our previous Statistics endpoint, and includes new metrics and customization capabilities.",
        "operationId": "GetAdsetReport",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/transactions/report": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "This Transactions endpoint provides transactions id related data.",
        "operationId": "GetTransactionsReport",
        "security": [
          {
            "oauth": [
              "MarketingSolutions_Analytics_Read"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://api.criteo.com/oauth2/token",
            "scopes": { }
          },
          "authorizationCode": {
            "authorizationUrl": "https://api.criteo.com/oauth2",
            "tokenUrl": "https://api.criteo.com/oauth2/token",
            "scopes": { }
          }
        }
      }
    }
  },
  "security": [
    {
      "oauth": [ ]
    }
  ],
  "tags": [
    {
      "name": "Advertiser"
    },
    {
      "name": "Analytics"
    },
    {
      "name": "Audience"
    },
    {
      "name": "Campaign"
    },
    {
      "name": "Catalog"
    },
    {
      "name": "Creative"
    },
    {
      "name": "Gateway"
    },
    {
      "name": "OnSiteRecommendation"
    },
    {
      "name": "Reco"
    }
  ],
  "x-samples-languages": [
    "java",
    "python",
    "php",
    "csharp",
    "javascript",
    "curl",
    "ruby"
  ]
}