{
  "openapi": "3.0.1",
  "info": {
    "title": "Criteo API",
    "description": "Criteo API - RetailMedia",
    "version": "Preview"
  },
  "servers": [
    {
      "url": "https://api.criteo.com"
    }
  ],
  "paths": {
    "/preview/retail-media/account-management/accounts/{accountId}/private-market-child-accounts": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "description": "Gets Private Market child accounts that are associated with the given account",
        "operationId": "GetPrivateMarketChildAccountsByAccountId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Accounts_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audience-segments": {
      "patch": {
        "tags": [
          "Audience"
        ],
        "description": "Updates the properties of all segments with a valid configuration, and returns the full segments. For those that cannot be updated, one or multiple errors are returned.",
        "operationId": "bulkUpdateAudienceSegments",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audience-segments/{audience-segment-id}/contact-list": {
      "get": {
        "tags": [
          "Audience"
        ],
        "description": "Returns the statistics of a contact list segment.",
        "operationId": "getAudienceSegmentContactListStatistics",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audience-segments/compute-sizes": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Gets the size of all segments. An error is returned for those whose size calculation is not supported.",
        "operationId": "computeAudienceSegmentsSizes",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audience-segments/create": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Creates all segments with a valid configuration, and returns the full segments. For those that cannot be created, one or multiple errors are returned.",
        "operationId": "bulkCreateAudienceSegments",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audience-segments/delete": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Delete the segments associated to the given IDs.",
        "operationId": "bulkDeleteAudienceSegments",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audience-segments/estimate-size": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Gets the size estimation of a non existent segment. An error is returned when size calculation is not supported.",
        "operationId": "estimateAudienceSegmentSize",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audience-segments/search": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Returns a list of segments that match the provided filters. If present, the filters are AND'ed together when applied.",
        "operationId": "searchAudienceSegments",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audiences": {
      "patch": {
        "tags": [
          "Audience"
        ],
        "description": "Updates the properties of all audiences with a valid configuration, and returns their IDs. For those that cannot be updated, one or multiple errors are returned.",
        "operationId": "bulkUpdateAudience",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audiences/compute-sizes": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Gets the size of all audiences. An error is returned for those whose size calculation is not supported.",
        "operationId": "computeAudiencesSizes",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audiences/create": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Creates all audiences with a valid configuration, and returns their IDs. For those that cannot be created, one or multiple errors are returned.",
        "operationId": "bulkCreateAudience",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audiences/delete": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Deletes the audiences associated to the given IDs.",
        "operationId": "bulkDeleteAudiences",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audiences/estimate-size": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Gets the size estimation of a non existent audience. An error is returned when size calculation is not supported.",
        "operationId": "estimateAudienceSize",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/audiences/search": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Returns a list of audiences that match the provided filters. If present, the filters are AND'ed together when applied.",
        "operationId": "searchAudiences",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/balances": {
      "get": {
        "tags": [
          "Balance"
        ],
        "description": "Gets page of balance objects for the given account id",
        "operationId": "GetBalancesByAccountId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Balance_Read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Balance"
        ],
        "description": "Create balance for the given account id",
        "operationId": "CreateBalanceByAccountId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Balance_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/balances/{balance-id}": {
      "patch": {
        "tags": [
          "Balance"
        ],
        "description": "Modify a balance for the given account id",
        "operationId": "UpdateBalanceV2",
        "security": [
          {
            "oauth": [
              "RetailMedia_Balance_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/creatives": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Create a creative for an account",
        "operationId": "CreateCreative",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/creatives/{creative-id}": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Get the specified creative",
        "operationId": "GetCreative",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "description": "Update a creative",
        "operationId": "UpdateCreative",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/creatives/search": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Get account creatives",
        "operationId": "SearchAccountCreatives",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{account-id}/line-items/cap-out-history": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Get the cap out history for line items",
        "operationId": "GetCapoutHistory",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{accountId}/grant-third-party-consent": {
      "post": {
        "tags": [
          "ThirdPartyAccounts"
        ],
        "summary": "",
        "description": "Grant third-party consent to a business application on behalf of a Private Market demand account",
        "operationId": "GrantThirdPartyConsent",
        "security": [
          {
            "oauth": [
              "RetailMedia_ThirdPartyAccounts_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/accounts/{accountId}/retailers/search": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Searches for retailers associated with the specified account based on provided search criteria",
        "operationId": "SearchAccountRetailers",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/auction-line-items/{lineItemId}": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Gets a sponsored product line item by its id.",
        "operationId": "GetAuctionLineItem",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "description": "Updates a Sponsored Products Line Item given a line item id and a request.",
        "operationId": "UpdateAuctionLineItem",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/audience-segments/{audience-segment-id}/contact-list/add-remove": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Add/remove identifiers to or from a retail-media contact list audience-segment, with external audience segment id.",
        "operationId": "AddRemoveContactListByAudienceSegment",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/audience-segments/{audience-segment-id}/contact-list/clear": {
      "post": {
        "tags": [
          "Audience"
        ],
        "description": "Delete all identifiers from a retail-media contact list audience-segment, with external audience segment id.",
        "operationId": "ClearContactListByAudienceSegment",
        "security": [
          {
            "oauth": [
              "RetailMedia_Audience_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/balances/{balance-id}/campaigns": {
      "get": {
        "tags": [
          "Balance"
        ],
        "description": "Gets page of campaigns for the given balanceId",
        "operationId": "GetCampaignsByBalanceId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Balance_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/balances/{balance-id}/campaigns/append": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "appends one or more campaigns to the specified balance",
        "operationId": "AppendCampaignsByBalanceId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/balances/{balanceId}/history": {
      "get": {
        "tags": [
          "Balance"
        ],
        "description": "Gets the balance's historical change data.",
        "operationId": "GetBalanceHistory",
        "security": [
          {
            "oauth": [
              "RetailMedia_Balance_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/brands/search": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Search for brands given a retailer ID and search term.",
        "operationId": "SearchBrands",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/campaigns/{campaign-id}/preferred-line-items": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Gets page of preferred line item objects for the given campaign id",
        "operationId": "GetPreferredLineItemsByCampaignId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Creates a new preferred line item with the specified settings",
        "operationId": "CreatePreferredLineItemByCampaignId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/campaigns/{campaignId}/auction-line-items": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Gets a page of sponsored product line items by campaign id.",
        "operationId": "GetAuctionLineItemsByCampaign",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Creates new auction line item with the specified settings",
        "operationId": "CreateAuctionLineItem",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/catalog/products/batch": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "description": "Used to publish a batch of operations to insert, update and deletes products.\n The batch is processed asynchronously.The response provides an operationToken which can be used to track\n the status of the report of the operation.",
        "operationId": "SubmitCatalogProductsBatch",
        "security": [
          {
            "oauth": [
              "RetailMedia_Catalog_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/catalog/products/batch/report/{operation-token}": {
      "get": {
        "tags": [
          "Catalog"
        ],
        "description": "Get the report of an asynchronous batch operation previously requested",
        "operationId": "GetCatalogProductsBatchReport",
        "security": [
          {
            "oauth": [
              "RetailMedia_Catalog_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/catalogs/{catalogId}/status": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Check the status of a catalog request.",
        "operationId": "GetCatalogStatus",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/catalogs/sku-retrieval": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Endpoint to search skus by text, retailer and sellers/brands.",
        "operationId": "SkuRetrieval_PostApiExternalV1CatalogsSkuRetrieval",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/catalogs/sku-search": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Endpoint to search skus by text, retailer and sellers/brands.",
        "operationId": "SkuSearch_PostApiExternalV1CatalogsSkuSearch",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/chatbot-catalogs/{catalogid}/product-recommendations": {
      "post": {
        "tags": [
          "OnSiteRecommendation"
        ],
        "description": "Ask a chatbot for a product recommendation",
        "operationId": "chatbotProductRecommendations",
        "security": [
          {
            "oauth": [
              "RetailMedia_OnSiteRecommendation_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/insights/share-of-voice": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "Generate a share of voice by category insight",
        "operationId": "GenerateShareOfVoiceInsight",
        "security": [
          {
            "oauth": [
              "RetailMedia_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/line-items/{line-item-id}/product-buttons": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Get LineItem Product Buttons",
        "operationId": "GetProductButtonsByLineItemId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/line-items/{line-item-id}/product-buttons/{product-button-id}": {
      "delete": {
        "tags": [
          "Campaign"
        ],
        "description": "Delete Specific Product Button",
        "operationId": "DeleteProductButtonByLineItemAndProductButtonId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Get Specific Product Button",
        "operationId": "GetProductButtonByLineItemAndProductButtonId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "description": "Update Specific Product Button",
        "operationId": "UpdateProductButtonByLineItemAndProductButtonId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/line-items/{line-item-id}/product-buttons/create": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Add Specific Product Buttons",
        "operationId": "AppendProductButtonByLineItemId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/line-items/{line-item-id}/products": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Retrieve a page of promoted products for a line item",
        "operationId": "FetchPromotedProducts",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/line-items/{line-item-id}/products/append": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Append a collection of promoted products to a line item",
        "operationId": "AppendPromotedProducts",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/line-items/{line-item-id}/products/delete": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Remove a collection of promoted products from a line item",
        "operationId": "DeletePromotedProducts",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/line-items/{line-item-id}/products/pause": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Pause a collection of promoted products associated with a line item",
        "operationId": "PausePromotedProducts",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/line-items/{line-item-id}/products/unpause": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Un-pause a collection of promoted products associated with a line item",
        "operationId": "UnpausePromotedProducts",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/me": {
      "get": {
        "tags": [
          "Gateway"
        ],
        "description": "Get information about the currently logged application",
        "operationId": "GetCurrentApplication",
        "security": [
          {
            "oauth": [ ]
          }
        ]
      }
    },
    "/preview/retail-media/preferred-line-items/{line-item-id}": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Gets the preferred line item for the given line item id",
        "operationId": "GetPreferredLineItemsByLineItemId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Campaign"
        ],
        "description": "Updates the preferred line item for the given line item id",
        "operationId": "UpdatePreferredLineItemByLineItemId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/reports/{reportId}/output": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "description": "Returns the output of an async report",
        "operationId": "GetAsyncExportOutput",
        "security": [
          {
            "oauth": [
              "RetailMedia_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/reports/{reportId}/status": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "description": "Returns the status of an async report",
        "operationId": "GetAsyncExportStatus",
        "security": [
          {
            "oauth": [
              "RetailMedia_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/reports/accounts": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "Returns an asynchronous Accounts Report\r\n<br />\r\nThis endpoint is subject to specific rate limits.",
        "operationId": "GenerateAsyncAccountsReport",
        "security": [
          {
            "oauth": [
              "RetailMedia_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/reports/campaigns": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "Return an asynchronous Campaigns Report\r\n<br />\r\nThis endpoint is subject to specific rate limits.",
        "operationId": "GenerateAsyncCampaignsReport",
        "security": [
          {
            "oauth": [
              "RetailMedia_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/reports/fillrate": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "Returns an asynchronous Fill Rate Report\r\n<br />\r\nThis endpoint is subject to specific rate limits.",
        "operationId": "GenerateAsyncFillRateReport",
        "security": [
          {
            "oauth": [
              "RetailMedia_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/reports/line-items": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "Returns an asynchronous Line Items Report\r\n<br />\r\nThis endpoint is subject to specific rate limits.",
        "operationId": "GenerateAsyncLineItemsReport",
        "security": [
          {
            "oauth": [
              "RetailMedia_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/reports/offsite": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "Returns an asynchronous Offsite Report\r\n<br />\r\nThis endpoint is subject to specific rate limits.",
        "operationId": "GenerateAsyncOffsiteReport",
        "security": [
          {
            "oauth": [
              "RetailMedia_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/reports/sync/attributed-transactions": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "Returns a synchronous Attributed Transactions Report",
        "operationId": "GenerateSyncAttributedTransactionsReport",
        "security": [
          {
            "oauth": [
              "RetailMedia_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/reports/sync/campaigns": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "Returns a synchronous Campaigns Report",
        "operationId": "GenerateSyncCampaignsReport",
        "security": [
          {
            "oauth": [
              "RetailMedia_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/reports/sync/line-items": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "Returns a synchronous Line Items Report",
        "operationId": "GenerateSyncLineItemsReport",
        "security": [
          {
            "oauth": [
              "RetailMedia_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/reports/unfilled-placements": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "description": "Returns an asynchronous Unfilled Placements Report\r\n<br />\r\nThis endpoint is subject to specific rate limits.",
        "operationId": "GenerateAsyncUnfilledPlacementsReport",
        "security": [
          {
            "oauth": [
              "RetailMedia_Analytics_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/retailers/{retailer-id}/cpc-rates": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Gets the minimum cpc bid for the retailer, and optionally the categories under the retailer",
        "operationId": "Retailer_GetApiExternalV1RetailerCpcRatesByRetailerId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/retailers/{retailer-id}/offers/update": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "description": "Update one or more offers by replacing each offer's price and availability with the given values",
        "operationId": "OfferUpdateV1",
        "security": [
          {
            "oauth": [
              "RetailMedia_Catalog_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/retailers/{retailer-id}/placements": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Gets all placement information for the given retailer",
        "operationId": "Retailer_GetApiExternalV1RetailerPlacementsByRetailerId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/retailers/{retailer-id}/products/set-buy-box-winners": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "description": "Update the buy box winner for one or more products",
        "operationId": "OfferSetBbwV1",
        "security": [
          {
            "oauth": [
              "RetailMedia_Catalog_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/retailers/{retailerId}/brands": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Gets the brands for the given retailer",
        "operationId": "Retailer_GetApiExternalV1RetailerBrandsByRetailerId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/retailers/{retailerId}/compute-display-min-bid": {
      "post": {
        "tags": [
          "Campaign"
        ],
        "description": "Computes the min bid for relevant page types based on the provided information",
        "operationId": "ComputeDisplayMinBidByRetailerId",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/retailers/{retailerId}/sellers/{seller}": {
      "get": {
        "tags": [
          "Campaign"
        ],
        "description": "Endpoint to get market place seller id and name",
        "operationId": "Seller_GetApiExternalV1RetailerByRetailerId}Sellers{seller",
        "security": [
          {
            "oauth": [
              "RetailMedia_Campaign_Read"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/third-party-accounts/{accountId}/brands/{brandId}/remove": {
      "post": {
        "tags": [
          "ThirdPartyAccounts"
        ],
        "description": "Attempt to remove the provided brand from the account.",
        "operationId": "RemoveThirdPartyAccountBrand",
        "security": [
          {
            "oauth": [
              "RetailMedia_ThirdPartyAccounts_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/third-party-accounts/{accountId}/brands/add": {
      "post": {
        "tags": [
          "ThirdPartyAccounts"
        ],
        "description": "add the provided brands to an account. This will not remove any existing brands.",
        "operationId": "AddThirdPartyAccountBrands",
        "security": [
          {
            "oauth": [
              "RetailMedia_ThirdPartyAccounts_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/third-party-accounts/{accountId}/create-brand-account": {
      "post": {
        "tags": [
          "ThirdPartyAccounts"
        ],
        "description": "Create a private market demand brand account under a given parent account.",
        "operationId": "CreateThirdPartyBrandAccount",
        "security": [
          {
            "oauth": [
              "RetailMedia_ThirdPartyAccounts_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/third-party-accounts/{accountId}/create-seller-account": {
      "post": {
        "tags": [
          "ThirdPartyAccounts"
        ],
        "description": "Create a private market demand seller account under a given parent account.",
        "operationId": "CreateThirdPartySellerAccount",
        "security": [
          {
            "oauth": [
              "RetailMedia_ThirdPartyAccounts_Manage"
            ]
          }
        ]
      }
    },
    "/preview/retail-media/third-party-accounts/{accountId}/sellers": {
      "put": {
        "tags": [
          "ThirdPartyAccounts"
        ],
        "description": "Update the list of sellers mapped to the account. This will override any existing mappings.",
        "operationId": "UpdateThirdPartyAccountSellers",
        "security": [
          {
            "oauth": [
              "RetailMedia_ThirdPartyAccounts_Manage"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://api.criteo.com/oauth2/token",
            "scopes": { }
          },
          "authorizationCode": {
            "authorizationUrl": "https://api.criteo.com/oauth2",
            "tokenUrl": "https://api.criteo.com/oauth2/token",
            "scopes": { }
          }
        }
      }
    }
  },
  "security": [
    {
      "oauth": [ ]
    }
  ],
  "tags": [
    {
      "name": "Accounts"
    },
    {
      "name": "Analytics"
    },
    {
      "name": "Audience"
    },
    {
      "name": "Balance"
    },
    {
      "name": "Campaign"
    },
    {
      "name": "Catalog"
    },
    {
      "name": "Gateway"
    },
    {
      "name": "OnSiteRecommendation"
    },
    {
      "name": "ThirdPartyAccounts"
    }
  ],
  "x-samples-languages": [
    "java",
    "python",
    "php",
    "csharp",
    "javascript",
    "curl",
    "ruby"
  ]
}