<?php
/**
 * GenerateTopProductsReportRequestAttributes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  criteo\api\marketingsolutions\experimental
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Criteo API
 *
 * Criteo API - MarketingSolutions
 *
 * The version of the OpenAPI document: Experimental
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace criteo\api\marketingsolutions\experimental\Model;

use \ArrayAccess;
use \criteo\api\marketingsolutions\experimental\ObjectSerializer;

/**
 * GenerateTopProductsReportRequestAttributes Class Doc Comment
 *
 * @category Class
 * @description This is the message defining the query for TopProducts report
 * @package  criteo\api\marketingsolutions\experimental
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GenerateTopProductsReportRequestAttributes implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GenerateTopProductsReportRequestAttributes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'ad_set_ids' => 'string[]',
        'ad_set_status' => 'string[]',
        'advertiser_id' => 'string',
        'brands' => 'string[]',
        'campaign_ids' => 'string[]',
        'category_ids' => 'string[]',
        'currency' => 'string',
        'dimensions' => 'string[]',
        'end_date' => '\DateTime',
        'limit' => 'int',
        'metrics' => 'string[]',
        'rank_products_by' => 'string',
        'start_date' => '\DateTime',
        'timezone' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'ad_set_ids' => null,
        'ad_set_status' => null,
        'advertiser_id' => null,
        'brands' => null,
        'campaign_ids' => null,
        'category_ids' => null,
        'currency' => null,
        'dimensions' => null,
        'end_date' => 'date-time',
        'limit' => 'int32',
        'metrics' => null,
        'rank_products_by' => null,
        'start_date' => 'date-time',
        'timezone' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'ad_set_ids' => true,
		'ad_set_status' => true,
		'advertiser_id' => false,
		'brands' => true,
		'campaign_ids' => true,
		'category_ids' => true,
		'currency' => false,
		'dimensions' => true,
		'end_date' => false,
		'limit' => false,
		'metrics' => true,
		'rank_products_by' => false,
		'start_date' => false,
		'timezone' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ad_set_ids' => 'adSetIds',
        'ad_set_status' => 'adSetStatus',
        'advertiser_id' => 'advertiserId',
        'brands' => 'brands',
        'campaign_ids' => 'campaignIds',
        'category_ids' => 'categoryIds',
        'currency' => 'currency',
        'dimensions' => 'dimensions',
        'end_date' => 'endDate',
        'limit' => 'limit',
        'metrics' => 'metrics',
        'rank_products_by' => 'rankProductsBy',
        'start_date' => 'startDate',
        'timezone' => 'timezone'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ad_set_ids' => 'setAdSetIds',
        'ad_set_status' => 'setAdSetStatus',
        'advertiser_id' => 'setAdvertiserId',
        'brands' => 'setBrands',
        'campaign_ids' => 'setCampaignIds',
        'category_ids' => 'setCategoryIds',
        'currency' => 'setCurrency',
        'dimensions' => 'setDimensions',
        'end_date' => 'setEndDate',
        'limit' => 'setLimit',
        'metrics' => 'setMetrics',
        'rank_products_by' => 'setRankProductsBy',
        'start_date' => 'setStartDate',
        'timezone' => 'setTimezone'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ad_set_ids' => 'getAdSetIds',
        'ad_set_status' => 'getAdSetStatus',
        'advertiser_id' => 'getAdvertiserId',
        'brands' => 'getBrands',
        'campaign_ids' => 'getCampaignIds',
        'category_ids' => 'getCategoryIds',
        'currency' => 'getCurrency',
        'dimensions' => 'getDimensions',
        'end_date' => 'getEndDate',
        'limit' => 'getLimit',
        'metrics' => 'getMetrics',
        'rank_products_by' => 'getRankProductsBy',
        'start_date' => 'getStartDate',
        'timezone' => 'getTimezone'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const AD_SET_STATUS_ACTIVE = 'Active';
    public const AD_SET_STATUS_NOT_RUNNING = 'NotRunning';
    public const AD_SET_STATUS_DEAD = 'Dead';
    public const DIMENSIONS_CAMPAIGN = 'Campaign';
    public const DIMENSIONS_CAMPAIGN_ID = 'CampaignId';
    public const DIMENSIONS_AD_SET = 'AdSet';
    public const DIMENSIONS_AD_SET_ID = 'AdSetId';
    public const DIMENSIONS_PRODUCT = 'Product';
    public const DIMENSIONS_PRODUCT_ID = 'ProductId';
    public const DIMENSIONS_CATEGORY = 'Category';
    public const DIMENSIONS_CATEGORY_ID = 'CategoryId';
    public const DIMENSIONS_ADVERTISER = 'Advertiser';
    public const DIMENSIONS_ADVERTISER_ID = 'AdvertiserId';
    public const DIMENSIONS_PRODUCT_URL = 'ProductUrl';
    public const DIMENSIONS_BRAND = 'Brand';
    public const METRICS_CLICKS = 'Clicks';
    public const METRICS_CTR = 'Ctr';
    public const METRICS_VISITS = 'Visits';
    public const METRICS_SALES = 'Sales';
    public const METRICS_COST = 'Cost';
    public const METRICS_REVENUE = 'Revenue';
    public const METRICS_DISPLAYS = 'Displays';
    public const RANK_PRODUCTS_BY_CLICKS = 'Clicks';
    public const RANK_PRODUCTS_BY_DISPLAYS = 'Displays';
    public const RANK_PRODUCTS_BY_SALES = 'Sales';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAdSetStatusAllowableValues()
    {
        return [
            self::AD_SET_STATUS_ACTIVE,
            self::AD_SET_STATUS_NOT_RUNNING,
            self::AD_SET_STATUS_DEAD,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDimensionsAllowableValues()
    {
        return [
            self::DIMENSIONS_CAMPAIGN,
            self::DIMENSIONS_CAMPAIGN_ID,
            self::DIMENSIONS_AD_SET,
            self::DIMENSIONS_AD_SET_ID,
            self::DIMENSIONS_PRODUCT,
            self::DIMENSIONS_PRODUCT_ID,
            self::DIMENSIONS_CATEGORY,
            self::DIMENSIONS_CATEGORY_ID,
            self::DIMENSIONS_ADVERTISER,
            self::DIMENSIONS_ADVERTISER_ID,
            self::DIMENSIONS_PRODUCT_URL,
            self::DIMENSIONS_BRAND,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMetricsAllowableValues()
    {
        return [
            self::METRICS_CLICKS,
            self::METRICS_CTR,
            self::METRICS_VISITS,
            self::METRICS_SALES,
            self::METRICS_COST,
            self::METRICS_REVENUE,
            self::METRICS_DISPLAYS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRankProductsByAllowableValues()
    {
        return [
            self::RANK_PRODUCTS_BY_CLICKS,
            self::RANK_PRODUCTS_BY_DISPLAYS,
            self::RANK_PRODUCTS_BY_SALES,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('ad_set_ids', $data ?? [], null);
        $this->setIfExists('ad_set_status', $data ?? [], null);
        $this->setIfExists('advertiser_id', $data ?? [], null);
        $this->setIfExists('brands', $data ?? [], null);
        $this->setIfExists('campaign_ids', $data ?? [], null);
        $this->setIfExists('category_ids', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], 'EUR');
        $this->setIfExists('dimensions', $data ?? [], null);
        $this->setIfExists('end_date', $data ?? [], null);
        $this->setIfExists('limit', $data ?? [], 200);
        $this->setIfExists('metrics', $data ?? [], null);
        $this->setIfExists('rank_products_by', $data ?? [], null);
        $this->setIfExists('start_date', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], 'UTC');
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['advertiser_id'] === null) {
            $invalidProperties[] = "'advertiser_id' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        if ($this->container['end_date'] === null) {
            $invalidProperties[] = "'end_date' can't be null";
        }
        if (!is_null($this->container['limit']) && ($this->container['limit'] > 200)) {
            $invalidProperties[] = "invalid value for 'limit', must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['limit']) && ($this->container['limit'] < 1)) {
            $invalidProperties[] = "invalid value for 'limit', must be bigger than or equal to 1.";
        }

        if ($this->container['rank_products_by'] === null) {
            $invalidProperties[] = "'rank_products_by' can't be null";
        }
        $allowedValues = $this->getRankProductsByAllowableValues();
        if (!is_null($this->container['rank_products_by']) && !in_array($this->container['rank_products_by'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'rank_products_by', must be one of '%s'",
                $this->container['rank_products_by'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['start_date'] === null) {
            $invalidProperties[] = "'start_date' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ad_set_ids
     *
     * @return string[]|null
     */
    public function getAdSetIds()
    {
        return $this->container['ad_set_ids'];
    }

    /**
     * Sets ad_set_ids
     *
     * @param string[]|null $ad_set_ids Optional list of ad set IDs to filter on. The ad sets must already exist. If empty, all ad sets will be included.
     *
     * @return self
     */
    public function setAdSetIds($ad_set_ids)
    {
        if (is_null($ad_set_ids)) {
            array_push($this->openAPINullablesSetToNull, 'ad_set_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ad_set_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ad_set_ids'] = $ad_set_ids;

        return $this;
    }

    /**
     * Gets ad_set_status
     *
     * @return string[]|null
     */
    public function getAdSetStatus()
    {
        return $this->container['ad_set_status'];
    }

    /**
     * Sets ad_set_status
     *
     * @param string[]|null $ad_set_status Optional list of ad set statuses to filter on. If empty, all ad sets will be included.
     *
     * @return self
     */
    public function setAdSetStatus($ad_set_status)
    {
        if (is_null($ad_set_status)) {
            array_push($this->openAPINullablesSetToNull, 'ad_set_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ad_set_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getAdSetStatusAllowableValues();
        if (!is_null($ad_set_status) && array_diff($ad_set_status, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'ad_set_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['ad_set_status'] = $ad_set_status;

        return $this;
    }

    /**
     * Gets advertiser_id
     *
     * @return string
     */
    public function getAdvertiserId()
    {
        return $this->container['advertiser_id'];
    }

    /**
     * Sets advertiser_id
     *
     * @param string $advertiser_id The advertiser ID to report on. The advertiser must already exist. At least one advertiser ID should be provided
     *
     * @return self
     */
    public function setAdvertiserId($advertiser_id)
    {
        if (is_null($advertiser_id)) {
            throw new \InvalidArgumentException('non-nullable advertiser_id cannot be null');
        }
        $this->container['advertiser_id'] = $advertiser_id;

        return $this;
    }

    /**
     * Gets brands
     *
     * @return string[]|null
     */
    public function getBrands()
    {
        return $this->container['brands'];
    }

    /**
     * Sets brands
     *
     * @param string[]|null $brands Optional list of brand names to filter on. If empty, all brands will be included.
     *
     * @return self
     */
    public function setBrands($brands)
    {
        if (is_null($brands)) {
            array_push($this->openAPINullablesSetToNull, 'brands');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('brands', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['brands'] = $brands;

        return $this;
    }

    /**
     * Gets campaign_ids
     *
     * @return string[]|null
     */
    public function getCampaignIds()
    {
        return $this->container['campaign_ids'];
    }

    /**
     * Sets campaign_ids
     *
     * @param string[]|null $campaign_ids Optional list of campaign IDs to filter on. The campaigns must already exist. If empty, all campaigns will be included.
     *
     * @return self
     */
    public function setCampaignIds($campaign_ids)
    {
        if (is_null($campaign_ids)) {
            array_push($this->openAPINullablesSetToNull, 'campaign_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('campaign_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['campaign_ids'] = $campaign_ids;

        return $this;
    }

    /**
     * Gets category_ids
     *
     * @return string[]|null
     */
    public function getCategoryIds()
    {
        return $this->container['category_ids'];
    }

    /**
     * Sets category_ids
     *
     * @param string[]|null $category_ids Optional list of product catalog category IDs to filter on. If empty, all categories will be included.
     *
     * @return self
     */
    public function setCategoryIds($category_ids)
    {
        if (is_null($category_ids)) {
            array_push($this->openAPINullablesSetToNull, 'category_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('category_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['category_ids'] = $category_ids;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency The currency used for the report. ISO 4217 code (three-letter capitals).
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets dimensions
     *
     * @return string[]|null
     */
    public function getDimensions()
    {
        return $this->container['dimensions'];
    }

    /**
     * Sets dimensions
     *
     * @param string[]|null $dimensions Optional list of dimensions for the report. If not provided, defaults to [ProductId, Product, ProductUrl]. When an ID dimension is requested (e.g., CampaignId), the corresponding name dimension (e.g., Campaign) is automatically included, and vice versa. This applies to the following pairs: CampaignId/Campaign, AdSetId/AdSet, ProductId/Product, CategoryId/Category, AdvertiserId/Advertiser.
     *
     * @return self
     */
    public function setDimensions($dimensions)
    {
        if (is_null($dimensions)) {
            array_push($this->openAPINullablesSetToNull, 'dimensions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dimensions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getDimensionsAllowableValues();
        if (!is_null($dimensions) && array_diff($dimensions, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'dimensions', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['dimensions'] = $dimensions;

        return $this;
    }

    /**
     * Gets end_date
     *
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->container['end_date'];
    }

    /**
     * Sets end_date
     *
     * @param \DateTime $end_date End date of the report. Date component of ISO 8601 format, any time or timezone component is ignored.
     *
     * @return self
     */
    public function setEndDate($end_date)
    {
        if (is_null($end_date)) {
            throw new \InvalidArgumentException('non-nullable end_date cannot be null');
        }
        $this->container['end_date'] = $end_date;

        return $this;
    }

    /**
     * Gets limit
     *
     * @return int|null
     */
    public function getLimit()
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     *
     * @param int|null $limit Optional maximum number of top products returned. Must be between 1 and 200.
     *
     * @return self
     */
    public function setLimit($limit)
    {
        if (is_null($limit)) {
            throw new \InvalidArgumentException('non-nullable limit cannot be null');
        }

        if (($limit > 200)) {
            throw new \InvalidArgumentException('invalid value for $limit when calling GenerateTopProductsReportRequestAttributes., must be smaller than or equal to 200.');
        }
        if (($limit < 1)) {
            throw new \InvalidArgumentException('invalid value for $limit when calling GenerateTopProductsReportRequestAttributes., must be bigger than or equal to 1.');
        }

        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets metrics
     *
     * @return string[]|null
     */
    public function getMetrics()
    {
        return $this->container['metrics'];
    }

    /**
     * Sets metrics
     *
     * @param string[]|null $metrics Optional list of metrics to report. If not provided, defaults to the metric specified in rankProductsBy.
     *
     * @return self
     */
    public function setMetrics($metrics)
    {
        if (is_null($metrics)) {
            array_push($this->openAPINullablesSetToNull, 'metrics');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('metrics', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getMetricsAllowableValues();
        if (!is_null($metrics) && array_diff($metrics, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'metrics', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['metrics'] = $metrics;

        return $this;
    }

    /**
     * Gets rank_products_by
     *
     * @return string
     */
    public function getRankProductsBy()
    {
        return $this->container['rank_products_by'];
    }

    /**
     * Sets rank_products_by
     *
     * @param string $rank_products_by Optional metric used to rank the top products. Allowed values: 'Clicks', 'Displays', 'Sales'.
     *
     * @return self
     */
    public function setRankProductsBy($rank_products_by)
    {
        if (is_null($rank_products_by)) {
            throw new \InvalidArgumentException('non-nullable rank_products_by cannot be null');
        }
        $allowedValues = $this->getRankProductsByAllowableValues();
        if (!in_array($rank_products_by, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'rank_products_by', must be one of '%s'",
                    $rank_products_by,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['rank_products_by'] = $rank_products_by;

        return $this;
    }

    /**
     * Gets start_date
     *
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     *
     * @param \DateTime $start_date Start date of the report. Date component of ISO 8601 format, any time or timezone component is ignored. Must be ≤ endDate.
     *
     * @return self
     */
    public function setStartDate($start_date)
    {
        if (is_null($start_date)) {
            throw new \InvalidArgumentException('non-nullable start_date cannot be null');
        }
        $this->container['start_date'] = $start_date;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string|null
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string|null $timezone Optional timezone used for the report. Timezone Database format (Tz).
     *
     * @return self
     */
    public function setTimezone($timezone)
    {
        if (is_null($timezone)) {
            array_push($this->openAPINullablesSetToNull, 'timezone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('timezone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


