/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.criteo.api.sdk.gradle

import org.gradle.api.Project
import org.gradle.api.Plugin
import com.criteo.api.sdk.gradle.tasks.GenerateSdkTask

class CriteoApiSdkGeneratorPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        project.run {   
            tasks.apply {
                register("generateCriteoApiSdk", GenerateSdkTask::class.java).configure {
                }
            }
        }
    }
}
