openapi: 3.0.1
info:
  description: Criteo API - RetailMedia
  title: Criteo API
  version: Experimental
servers:
- url: https://api.criteo.com
security:
- oauth: []
tags:
- name: Accounts
- name: Analytics
- name: Audience
- name: Balance
- name: Campaign
- name: Catalog
- name: Gateway
- name: OnSiteRecommendation
- name: ThirdPartyAccounts
paths:
  /experimental/retail-media/account-management/accounts/{accountId}/private-market-child-accounts:
    get:
      description: Gets Private Market child accounts that are associated with the
        given account
      operationId: GetPrivateMarketChildAccountsByAccountId
      security:
      - oauth:
        - RetailMedia_Accounts_Read
      summary: "/experimental/retail-media/account-management/accounts/{accountId}/private-market-child-accounts"
      tags:
      - Accounts
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audience-segments:
    patch:
      description: "Updates the properties of all segments with a valid configuration,\
        \ and returns the full segments. For those that cannot be updated, one or\
        \ multiple errors are returned."
      operationId: bulkUpdateAudienceSegments
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/audience-segments"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audience-segments/{audience-segment-id}/contact-list:
    get:
      description: Returns the statistics of a contact list segment.
      operationId: getAudienceSegmentContactListStatistics
      security:
      - oauth:
        - RetailMedia_Audience_Read
      summary: "/experimental/retail-media/accounts/{account-id}/audience-segments/{audience-segment-id}/contact-list"
      tags:
      - Audience
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audience-segments/compute-sizes:
    post:
      description: Gets the size of all segments. An error is returned for those whose
        size calculation is not supported.
      operationId: computeAudienceSegmentsSizes
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/audience-segments/compute-sizes"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audience-segments/create:
    post:
      description: "Creates all segments with a valid configuration, and returns the\
        \ full segments. For those that cannot be created, one or multiple errors\
        \ are returned."
      operationId: bulkCreateAudienceSegments
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/audience-segments/create"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audience-segments/delete:
    post:
      description: Delete the segments associated to the given IDs.
      operationId: bulkDeleteAudienceSegments
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/audience-segments/delete"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audience-segments/estimate-size:
    post:
      description: Gets the size estimation of a non existent segment. An error is
        returned when size calculation is not supported.
      operationId: estimateAudienceSegmentSize
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/audience-segments/estimate-size"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audience-segments/search:
    post:
      description: "Returns a list of segments that match the provided filters. If\
        \ present, the filters are AND'ed together when applied."
      operationId: searchAudienceSegments
      security:
      - oauth:
        - RetailMedia_Audience_Read
      summary: "/experimental/retail-media/accounts/{account-id}/audience-segments/search"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audiences:
    patch:
      description: "Updates the properties of all audiences with a valid configuration,\
        \ and returns their IDs. For those that cannot be updated, one or multiple\
        \ errors are returned."
      operationId: bulkUpdateAudience
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/audiences"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audiences/compute-sizes:
    post:
      description: Gets the size of all audiences. An error is returned for those
        whose size calculation is not supported.
      operationId: computeAudiencesSizes
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/audiences/compute-sizes"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audiences/create:
    post:
      description: "Creates all audiences with a valid configuration, and returns\
        \ their IDs. For those that cannot be created, one or multiple errors are\
        \ returned."
      operationId: bulkCreateAudience
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/audiences/create"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audiences/delete:
    post:
      description: Deletes the audiences associated to the given IDs.
      operationId: bulkDeleteAudiences
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/audiences/delete"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audiences/estimate-size:
    post:
      description: Gets the size estimation of a non existent audience. An error is
        returned when size calculation is not supported.
      operationId: estimateAudienceSize
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/audiences/estimate-size"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/audiences/search:
    post:
      description: "Returns a list of audiences that match the provided filters. If\
        \ present, the filters are AND'ed together when applied."
      operationId: searchAudiences
      security:
      - oauth:
        - RetailMedia_Audience_Read
      summary: "/experimental/retail-media/accounts/{account-id}/audiences/search"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/balances/{balance-id}:
    patch:
      description: Modify a balance for the given account id
      operationId: UpdateBalanceV1
      security:
      - oauth:
        - RetailMedia_Balance_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/balances/{balance-id}"
      tags:
      - Balance
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/creatives:
    post:
      description: Create a creative for an account
      operationId: CreateCreative
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/creatives"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/creatives/{creative-id}:
    get:
      description: Get the specified creative
      operationId: GetCreative
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/accounts/{account-id}/creatives/{creative-id}"
      tags:
      - Campaign
      x-accepts: application/json
    put:
      description: Update a creative
      operationId: UpdateCreative
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/accounts/{account-id}/creatives/{creative-id}"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/creatives/search:
    post:
      description: Get account creatives
      operationId: SearchAccountCreatives
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/accounts/{account-id}/creatives/search"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{account-id}/line-items/cap-out-history:
    post:
      description: Get the cap out history for line items
      operationId: GetCapoutHistory
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/accounts/{account-id}/line-items/cap-out-history"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{accountId}/balances:
    get:
      description: Gets page of balance objects for the given account id.
      operationId: GetPageOfBalancesV1
      security:
      - oauth:
        - RetailMedia_Balance_Read
      summary: "/experimental/retail-media/accounts/{accountId}/balances"
      tags:
      - Balance
      x-accepts: application/json
  /experimental/retail-media/accounts/{accountId}/grant-third-party-consent:
    post:
      description: Grant third-party consent to a business application on behalf of
        a Private Market demand account
      operationId: GrantThirdPartyConsent
      security:
      - oauth:
        - RetailMedia_ThirdPartyAccounts_Manage
      summary: "/experimental/retail-media/accounts/{accountId}/grant-third-party-consent"
      tags:
      - ThirdPartyAccounts
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/accounts/{accountId}/retailers/search:
    post:
      description: Searches for retailers associated with the specified account and
        returns budget model availability for each retailer
      operationId: SearchAccountRetailers
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/accounts/{accountId}/retailers/search"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/auction-line-items/{lineItemId}:
    get:
      description: Gets a sponsored product line item by its id.
      operationId: GetAuctionLineItem
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/auction-line-items/{lineItemId}"
      tags:
      - Campaign
      x-accepts: application/json
    put:
      description: Updates a Sponsored Products Line Item given a line item id and
        a request.
      operationId: UpdateAuctionLineItem
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/auction-line-items/{lineItemId}"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/audience-segments/{audience-segment-id}/contact-list/add-remove:
    post:
      description: "Add/remove identifiers to or from a retail-media contact list\
        \ audience-segment, with external audience segment id."
      operationId: AddRemoveContactListByAudienceSegment
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: "/experimental/retail-media/audience-segments/{audience-segment-id}/contact-list/add-remove"
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/audience-segments/{audience-segment-id}/contact-list/clear:
    post:
      description: "Delete all identifiers from a retail-media contact list audience-segment,\
        \ with external audience segment id."
      operationId: ClearContactListByAudienceSegment
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: "/experimental/retail-media/audience-segments/{audience-segment-id}/contact-list/clear"
      tags:
      - Audience
      x-accepts: application/json
  /experimental/retail-media/balances/{balanceId}:
    get:
      description: Get a balance for the given balance id.
      operationId: GetBalanceV1
      security:
      - oauth:
        - RetailMedia_Balance_Read
      summary: "/experimental/retail-media/balances/{balanceId}"
      tags:
      - Balance
      x-accepts: application/json
  /experimental/retail-media/balances/{balanceId}/campaigns/append:
    post:
      description: Appends one or more campaigns to the specified balance
      operationId: AppendCampaignsToBalanceV1
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/balances/{balanceId}/campaigns/append"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/balances/{balanceId}/campaigns/delete:
    post:
      description: Deletes one or more campaigns on the specified balance
      operationId: DeleteCampaignsFromBalanceV1
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/balances/{balanceId}/campaigns/delete"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/balances/{balanceId}/history:
    get:
      description: Gets the balance's historical change data.
      operationId: GetBalanceHistoryV1
      security:
      - oauth:
        - RetailMedia_Balance_Read
      summary: "/experimental/retail-media/balances/{balanceId}/history"
      tags:
      - Balance
      x-accepts: application/json
  /experimental/retail-media/brands/search:
    post:
      description: Search for brands given a retailer ID and search term.
      operationId: SearchBrands
      security:
      - oauth:
        - RetailMedia_Accounts_Read
      summary: /experimental/retail-media/brands/search
      tags:
      - Accounts
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/campaigns/{campaign-id}/preferred-line-items:
    get:
      description: Gets page of preferred line item objects for the given campaign
        id
      operationId: GetPreferredLineItemsByCampaignId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/campaigns/{campaign-id}/preferred-line-items"
      tags:
      - Campaign
      x-accepts: application/json
    post:
      description: Creates a new preferred line item with the specified settings
      operationId: CreatePreferredLineItemByCampaignId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/campaigns/{campaign-id}/preferred-line-items"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/campaigns/{campaignId}/auction-line-items:
    get:
      description: Gets a page of sponsored product line items by campaign id.
      operationId: GetAuctionLineItemsByCampaign
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/campaigns/{campaignId}/auction-line-items"
      tags:
      - Campaign
      x-accepts: application/json
    post:
      description: Creates new auction line item with the specified settings
      operationId: CreateAuctionLineItem
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/campaigns/{campaignId}/auction-line-items"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/catalog/merchants/{merchantId}/store-inventory/delete:
    post:
      description: Used to publish a batch of store inventories to delete. The batch
        is processed asynchronously.
      operationId: DeleteStoreInventoryPerMerchantId
      security:
      - oauth:
        - RetailMedia_Catalog_Manage
      summary: "/experimental/retail-media/catalog/merchants/{merchantId}/store-inventory/delete"
      tags:
      - Catalog
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/catalog/merchants/{merchantId}/store-inventory/upsert:
    post:
      description: Used to publish a batch of store inventories to upsert. The batch
        is processed asynchronously.
      operationId: UpsertStoreInventoryPerMerchantId
      security:
      - oauth:
        - RetailMedia_Catalog_Manage
      summary: "/experimental/retail-media/catalog/merchants/{merchantId}/store-inventory/upsert"
      tags:
      - Catalog
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/catalog/products/batch:
    post:
      description: |-
        Used to publish a batch of operations to insert, update and deletes products.
         The batch is processed asynchronously.The response provides an operationToken which can be used to track
         the status of the report of the operation.
      operationId: SubmitCatalogProductsBatch
      security:
      - oauth:
        - RetailMedia_Catalog_Manage
      summary: /experimental/retail-media/catalog/products/batch
      tags:
      - Catalog
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/catalog/products/batch/report/{operation-token}:
    get:
      description: Get the report of an asynchronous batch operation previously requested
      operationId: GetCatalogProductsBatchReport
      security:
      - oauth:
        - RetailMedia_Catalog_Read
      summary: "/experimental/retail-media/catalog/products/batch/report/{operation-token}"
      tags:
      - Catalog
      x-accepts: application/json
  /experimental/retail-media/catalogs/{catalogId}/status:
    get:
      description: Check the status of a catalog request.
      operationId: GetCatalogStatus
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/catalogs/{catalogId}/status"
      tags:
      - Campaign
      x-accepts: application/json
  /experimental/retail-media/chatbot-catalogs/{catalogid}/product-recommendations:
    post:
      description: Ask a chatbot for a product recommendation
      operationId: chatbotProductRecommendations
      security:
      - oauth:
        - RetailMedia_OnSiteRecommendation_Read
      summary: "/experimental/retail-media/chatbot-catalogs/{catalogid}/product-recommendations"
      tags:
      - OnSiteRecommendation
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/insights/{insightId}/output:
    get:
      description: Returns the output of an async insight
      operationId: GetInsightReportOutput
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: "/experimental/retail-media/insights/{insightId}/output"
      tags:
      - Analytics
      x-accepts: application/json
  /experimental/retail-media/insights/{insightId}/status:
    get:
      description: Returns the status of an async insight
      operationId: GetInsightReportStatus
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: "/experimental/retail-media/insights/{insightId}/status"
      tags:
      - Analytics
      x-accepts: application/json
  /experimental/retail-media/insights/digital-shelf-intelligence:
    post:
      description: Generate a Digital Shelf Intelligence insight
      operationId: GenerateDigitalShelfIntelligenceInsight
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: /experimental/retail-media/insights/digital-shelf-intelligence
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/insights/share-of-voice:
    post:
      description: Generate a share of voice insight
      operationId: GenerateShareOfVoiceInsight
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: /experimental/retail-media/insights/share-of-voice
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/line-items/{line-item-id}/product-buttons:
    get:
      description: Get LineItem Product Buttons
      operationId: GetProductButtonsByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/line-items/{line-item-id}/product-buttons"
      tags:
      - Campaign
      x-accepts: application/json
  /experimental/retail-media/line-items/{line-item-id}/product-buttons/{product-button-id}:
    delete:
      description: Delete Specific Product Button
      operationId: DeleteProductButtonByLineItemAndProductButtonId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/line-items/{line-item-id}/product-buttons/{product-button-id}"
      tags:
      - Campaign
      x-accepts: application/json
    get:
      description: Get Specific Product Button
      operationId: GetProductButtonByLineItemAndProductButtonId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/line-items/{line-item-id}/product-buttons/{product-button-id}"
      tags:
      - Campaign
      x-accepts: application/json
    put:
      description: Update Specific Product Button
      operationId: UpdateProductButtonByLineItemAndProductButtonId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/line-items/{line-item-id}/product-buttons/{product-button-id}"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/line-items/{line-item-id}/product-buttons/create:
    post:
      description: Add Specific Product Buttons
      operationId: AppendProductButtonByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/line-items/{line-item-id}/product-buttons/create"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/line-items/{line-item-id}/products:
    get:
      description: Retrieve a page of promoted products for a line item
      operationId: FetchPromotedProducts
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/line-items/{line-item-id}/products"
      tags:
      - Campaign
      x-accepts: application/json
  /experimental/retail-media/line-items/{line-item-id}/products/append:
    post:
      description: Append a collection of promoted products to a line item
      operationId: AppendPromotedProducts
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/line-items/{line-item-id}/products/append"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/line-items/{line-item-id}/products/delete:
    post:
      description: Remove a collection of promoted products from a line item
      operationId: DeletePromotedProducts
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/line-items/{line-item-id}/products/delete"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/line-items/{line-item-id}/products/pause:
    post:
      description: Pause a collection of promoted products associated with a line
        item
      operationId: PausePromotedProducts
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/line-items/{line-item-id}/products/pause"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/line-items/{line-item-id}/products/unpause:
    post:
      description: Un-pause a collection of promoted products associated with a line
        item
      operationId: UnpausePromotedProducts
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/line-items/{line-item-id}/products/unpause"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/me:
    get:
      description: Get information about the currently logged application
      operationId: GetCurrentApplication
      security:
      - oauth: []
      summary: /experimental/retail-media/me
      tags:
      - Gateway
      x-accepts: application/json
  /experimental/retail-media/preferred-line-items/{line-item-id}:
    get:
      description: Gets the preferred line item for the given line item id
      operationId: GetPreferredLineItemsByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/preferred-line-items/{line-item-id}"
      tags:
      - Campaign
      x-accepts: application/json
    put:
      description: Updates the preferred line item for the given line item id
      operationId: UpdatePreferredLineItemByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: "/experimental/retail-media/preferred-line-items/{line-item-id}"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/reports/{reportId}/output:
    get:
      description: Returns the output of an async report
      operationId: GetAsyncExportOutput
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: "/experimental/retail-media/reports/{reportId}/output"
      tags:
      - Analytics
      x-accepts: application/json
  /experimental/retail-media/reports/{reportId}/status:
    get:
      description: Returns the status of an async report
      operationId: GetAsyncExportStatus
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: "/experimental/retail-media/reports/{reportId}/status"
      tags:
      - Analytics
      x-accepts: application/json
  /experimental/retail-media/reports/accounts:
    post:
      description: "Returns an asynchronous Accounts Report\r\n<br />\r\nThis endpoint\
        \ is subject to specific rate limits."
      operationId: GenerateAsyncAccountsReportV2
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: /experimental/retail-media/reports/accounts
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/reports/campaigns:
    post:
      description: "Return an asynchronous Campaigns Report\r\n<br />\r\nThis endpoint\
        \ is subject to specific rate limits."
      operationId: GenerateAsyncCampaignsReportV2
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: /experimental/retail-media/reports/campaigns
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/reports/fillrate:
    post:
      description: "Returns an asynchronous Fill Rate Report\r\n<br />\r\nThis endpoint\
        \ is subject to specific rate limits."
      operationId: GenerateAsyncFillRateReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: /experimental/retail-media/reports/fillrate
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/reports/line-items:
    post:
      description: "Returns an asynchronous Line Items Report\r\n<br />\r\nThis endpoint\
        \ is subject to specific rate limits."
      operationId: GenerateAsyncLineItemsReportV2
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: /experimental/retail-media/reports/line-items
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/reports/offsite:
    post:
      description: "Returns an asynchronous Offsite Report\r\n<br />\r\nThis endpoint\
        \ is subject to specific rate limits."
      operationId: GenerateAsyncOffsiteReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: /experimental/retail-media/reports/offsite
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/reports/sync/attributed-transactions:
    post:
      description: Returns a synchronous Attributed Transactions Report
      operationId: GenerateSyncAttributedTransactionsReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: /experimental/retail-media/reports/sync/attributed-transactions
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/reports/sync/campaigns:
    post:
      description: Returns a synchronous Campaigns Report
      operationId: GenerateSyncCampaignsReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: /experimental/retail-media/reports/sync/campaigns
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/reports/sync/line-items:
    post:
      description: Returns a synchronous Line Items Report
      operationId: GenerateSyncLineItemsReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: /experimental/retail-media/reports/sync/line-items
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/reports/sync/real-time-performance:
    post:
      description: "Returns a synchronous Real Time Performance Report. Returns empty\
        \ rows; metadata includes dataCompleteThrough (latest time from streaming\
        \ table in the request timezone).\r\n<br />\r\nThis endpoint is subject to\
        \ specific rate limits."
      operationId: GenerateSyncRealTimePerformanceReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: /experimental/retail-media/reports/sync/real-time-performance
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/reports/unfilled-placements:
    post:
      description: "Returns an asynchronous Unfilled Placements Report\r\n<br />\r\
        \nThis endpoint is subject to specific rate limits."
      operationId: GenerateAsyncUnfilledPlacementsReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: /experimental/retail-media/reports/unfilled-placements
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/retailers/{retailer-id}/offers/update:
    post:
      description: Update one or more offers by replacing each offer's price and availability
        with the given values
      operationId: OfferUpdateV1
      security:
      - oauth:
        - RetailMedia_Catalog_Manage
      summary: "/experimental/retail-media/retailers/{retailer-id}/offers/update"
      tags:
      - Catalog
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/retailers/{retailer-id}/products/set-buy-box-winners:
    post:
      description: Update the buy box winner for one or more products
      operationId: OfferSetBbwV1
      security:
      - oauth:
        - RetailMedia_Catalog_Manage
      summary: "/experimental/retail-media/retailers/{retailer-id}/products/set-buy-box-winners"
      tags:
      - Catalog
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/retailers/{retailerId}/compute-display-min-bid:
    post:
      description: Computes the min bid for relevant page types based on the provided
        information
      operationId: ComputeDisplayMinBidByRetailerId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: "/experimental/retail-media/retailers/{retailerId}/compute-display-min-bid"
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/third-party-accounts/{accountId}/brands/{brandId}/remove:
    post:
      description: Attempt to remove the provided brand from the account.
      operationId: RemoveThirdPartyAccountBrand
      security:
      - oauth:
        - RetailMedia_ThirdPartyAccounts_Manage
      summary: "/experimental/retail-media/third-party-accounts/{accountId}/brands/{brandId}/remove"
      tags:
      - ThirdPartyAccounts
      x-accepts: application/json
  /experimental/retail-media/third-party-accounts/{accountId}/brands/add:
    post:
      description: add the provided brands to an account. This will not remove any
        existing brands.
      operationId: AddThirdPartyAccountBrands
      security:
      - oauth:
        - RetailMedia_ThirdPartyAccounts_Manage
      summary: "/experimental/retail-media/third-party-accounts/{accountId}/brands/add"
      tags:
      - ThirdPartyAccounts
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/third-party-accounts/{accountId}/create-brand-account:
    post:
      description: Create a private market demand brand account under a given parent
        account.
      operationId: CreateThirdPartyBrandAccount
      security:
      - oauth:
        - RetailMedia_ThirdPartyAccounts_Manage
      summary: "/experimental/retail-media/third-party-accounts/{accountId}/create-brand-account"
      tags:
      - ThirdPartyAccounts
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/third-party-accounts/{accountId}/create-seller-account:
    post:
      description: Create a private market demand seller account under a given parent
        account.
      operationId: CreateThirdPartySellerAccount
      security:
      - oauth:
        - RetailMedia_ThirdPartyAccounts_Manage
      summary: "/experimental/retail-media/third-party-accounts/{accountId}/create-seller-account"
      tags:
      - ThirdPartyAccounts
      x-content-type: application/json
      x-accepts: application/json
  /experimental/retail-media/third-party-accounts/{accountId}/sellers:
    put:
      description: Update the list of sellers mapped to the account. This will override
        any existing mappings.
      operationId: UpdateThirdPartyAccountSellers
      security:
      - oauth:
        - RetailMedia_ThirdPartyAccounts_Manage
      summary: "/experimental/retail-media/third-party-accounts/{accountId}/sellers"
      tags:
      - ThirdPartyAccounts
      x-content-type: application/json
      x-accepts: application/json
components:
  securitySchemes:
    oauth:
      flows:
        authorizationCode:
          authorizationUrl: https://api.criteo.com/oauth2
          scopes: {}
          tokenUrl: https://api.criteo.com/oauth2/token
        clientCredentials:
          scopes: {}
          tokenUrl: https://api.criteo.com/oauth2/token
      type: oauth2
x-samples-languages:
- java
- python
- php
- csharp
- javascript
- curl
- ruby

