/*
 * Criteo API
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: 2026-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.retailmedia.v2026_01.api;

import com.criteo.api.retailmedia.v2026_01.ApiCallback;
import com.criteo.api.retailmedia.v2026_01.ApiClient;
import com.criteo.api.retailmedia.v2026_01.ApiException;
import com.criteo.api.retailmedia.v2026_01.ApiResponse;
import com.criteo.api.retailmedia.v2026_01.Configuration;
import com.criteo.api.retailmedia.v2026_01.Pair;
import com.criteo.api.retailmedia.v2026_01.ProgressRequestBody;
import com.criteo.api.retailmedia.v2026_01.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.criteo.api.retailmedia.v2026_01.model.AsyncAccountsReportRequest;
import com.criteo.api.retailmedia.v2026_01.model.AsyncCampaignsReportRequest;
import com.criteo.api.retailmedia.v2026_01.model.AsyncFillRateReportRequest;
import com.criteo.api.retailmedia.v2026_01.model.AsyncLineItemsReportRequest;
import com.criteo.api.retailmedia.v2026_01.model.AsyncReportResponse;
import com.criteo.api.retailmedia.v2026_01.model.AsyncRevenueReportRequest;
import com.criteo.api.retailmedia.v2026_01.model.AsyncUnfilledPlacementsReportRequest;
import java.io.File;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class AnalyticsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AnalyticsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AnalyticsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for generateAsyncAccountsReportV2
     * @param asyncAccountsReportRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateAsyncAccountsReportV2Call(AsyncAccountsReportRequest asyncAccountsReportRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = asyncAccountsReportRequest;

        // create path and map variables
        String localVarPath = "/2026-01/retail-media/reports/accounts";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth", "oauth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateAsyncAccountsReportV2ValidateBeforeCall(AsyncAccountsReportRequest asyncAccountsReportRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'asyncAccountsReportRequest' is set
        if (asyncAccountsReportRequest == null) {
            throw new ApiException("Missing the required parameter 'asyncAccountsReportRequest' when calling generateAsyncAccountsReportV2(Async)");
        }

        return generateAsyncAccountsReportV2Call(asyncAccountsReportRequest, _callback);

    }

    /**
     * /2026-01/retail-media/reports/accounts
     * Returns an asynchronous Accounts Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncAccountsReportRequest  (required)
     * @return AsyncReportResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public AsyncReportResponse generateAsyncAccountsReportV2(AsyncAccountsReportRequest asyncAccountsReportRequest) throws ApiException {
        ApiResponse<AsyncReportResponse> localVarResp = generateAsyncAccountsReportV2WithHttpInfo(asyncAccountsReportRequest);
        return localVarResp.getData();
    }

    /**
     * /2026-01/retail-media/reports/accounts
     * Returns an asynchronous Accounts Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncAccountsReportRequest  (required)
     * @return ApiResponse&lt;AsyncReportResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AsyncReportResponse> generateAsyncAccountsReportV2WithHttpInfo(AsyncAccountsReportRequest asyncAccountsReportRequest) throws ApiException {
        okhttp3.Call localVarCall = generateAsyncAccountsReportV2ValidateBeforeCall(asyncAccountsReportRequest, null);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /2026-01/retail-media/reports/accounts (asynchronously)
     * Returns an asynchronous Accounts Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncAccountsReportRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateAsyncAccountsReportV2Async(AsyncAccountsReportRequest asyncAccountsReportRequest, final ApiCallback<AsyncReportResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateAsyncAccountsReportV2ValidateBeforeCall(asyncAccountsReportRequest, _callback);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for generateAsyncCampaignsReportV2
     * @param asyncCampaignsReportRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateAsyncCampaignsReportV2Call(AsyncCampaignsReportRequest asyncCampaignsReportRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = asyncCampaignsReportRequest;

        // create path and map variables
        String localVarPath = "/2026-01/retail-media/reports/campaigns";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth", "oauth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateAsyncCampaignsReportV2ValidateBeforeCall(AsyncCampaignsReportRequest asyncCampaignsReportRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'asyncCampaignsReportRequest' is set
        if (asyncCampaignsReportRequest == null) {
            throw new ApiException("Missing the required parameter 'asyncCampaignsReportRequest' when calling generateAsyncCampaignsReportV2(Async)");
        }

        return generateAsyncCampaignsReportV2Call(asyncCampaignsReportRequest, _callback);

    }

    /**
     * /2026-01/retail-media/reports/campaigns
     * Return an asynchronous Campaigns Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncCampaignsReportRequest  (required)
     * @return AsyncReportResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public AsyncReportResponse generateAsyncCampaignsReportV2(AsyncCampaignsReportRequest asyncCampaignsReportRequest) throws ApiException {
        ApiResponse<AsyncReportResponse> localVarResp = generateAsyncCampaignsReportV2WithHttpInfo(asyncCampaignsReportRequest);
        return localVarResp.getData();
    }

    /**
     * /2026-01/retail-media/reports/campaigns
     * Return an asynchronous Campaigns Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncCampaignsReportRequest  (required)
     * @return ApiResponse&lt;AsyncReportResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AsyncReportResponse> generateAsyncCampaignsReportV2WithHttpInfo(AsyncCampaignsReportRequest asyncCampaignsReportRequest) throws ApiException {
        okhttp3.Call localVarCall = generateAsyncCampaignsReportV2ValidateBeforeCall(asyncCampaignsReportRequest, null);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /2026-01/retail-media/reports/campaigns (asynchronously)
     * Return an asynchronous Campaigns Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncCampaignsReportRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateAsyncCampaignsReportV2Async(AsyncCampaignsReportRequest asyncCampaignsReportRequest, final ApiCallback<AsyncReportResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateAsyncCampaignsReportV2ValidateBeforeCall(asyncCampaignsReportRequest, _callback);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for generateAsyncFillRateReport
     * @param asyncFillRateReportRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateAsyncFillRateReportCall(AsyncFillRateReportRequest asyncFillRateReportRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = asyncFillRateReportRequest;

        // create path and map variables
        String localVarPath = "/2026-01/retail-media/reports/fillrate";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth", "oauth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateAsyncFillRateReportValidateBeforeCall(AsyncFillRateReportRequest asyncFillRateReportRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'asyncFillRateReportRequest' is set
        if (asyncFillRateReportRequest == null) {
            throw new ApiException("Missing the required parameter 'asyncFillRateReportRequest' when calling generateAsyncFillRateReport(Async)");
        }

        return generateAsyncFillRateReportCall(asyncFillRateReportRequest, _callback);

    }

    /**
     * /2026-01/retail-media/reports/fillrate
     * Returns an asynchronous Fill Rate Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncFillRateReportRequest  (required)
     * @return AsyncReportResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public AsyncReportResponse generateAsyncFillRateReport(AsyncFillRateReportRequest asyncFillRateReportRequest) throws ApiException {
        ApiResponse<AsyncReportResponse> localVarResp = generateAsyncFillRateReportWithHttpInfo(asyncFillRateReportRequest);
        return localVarResp.getData();
    }

    /**
     * /2026-01/retail-media/reports/fillrate
     * Returns an asynchronous Fill Rate Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncFillRateReportRequest  (required)
     * @return ApiResponse&lt;AsyncReportResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AsyncReportResponse> generateAsyncFillRateReportWithHttpInfo(AsyncFillRateReportRequest asyncFillRateReportRequest) throws ApiException {
        okhttp3.Call localVarCall = generateAsyncFillRateReportValidateBeforeCall(asyncFillRateReportRequest, null);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /2026-01/retail-media/reports/fillrate (asynchronously)
     * Returns an asynchronous Fill Rate Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncFillRateReportRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateAsyncFillRateReportAsync(AsyncFillRateReportRequest asyncFillRateReportRequest, final ApiCallback<AsyncReportResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateAsyncFillRateReportValidateBeforeCall(asyncFillRateReportRequest, _callback);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for generateAsyncLineItemsReportV2
     * @param asyncLineItemsReportRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateAsyncLineItemsReportV2Call(AsyncLineItemsReportRequest asyncLineItemsReportRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = asyncLineItemsReportRequest;

        // create path and map variables
        String localVarPath = "/2026-01/retail-media/reports/line-items";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth", "oauth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateAsyncLineItemsReportV2ValidateBeforeCall(AsyncLineItemsReportRequest asyncLineItemsReportRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'asyncLineItemsReportRequest' is set
        if (asyncLineItemsReportRequest == null) {
            throw new ApiException("Missing the required parameter 'asyncLineItemsReportRequest' when calling generateAsyncLineItemsReportV2(Async)");
        }

        return generateAsyncLineItemsReportV2Call(asyncLineItemsReportRequest, _callback);

    }

    /**
     * /2026-01/retail-media/reports/line-items
     * Returns an asynchronous Line Items Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncLineItemsReportRequest  (required)
     * @return AsyncReportResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public AsyncReportResponse generateAsyncLineItemsReportV2(AsyncLineItemsReportRequest asyncLineItemsReportRequest) throws ApiException {
        ApiResponse<AsyncReportResponse> localVarResp = generateAsyncLineItemsReportV2WithHttpInfo(asyncLineItemsReportRequest);
        return localVarResp.getData();
    }

    /**
     * /2026-01/retail-media/reports/line-items
     * Returns an asynchronous Line Items Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncLineItemsReportRequest  (required)
     * @return ApiResponse&lt;AsyncReportResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AsyncReportResponse> generateAsyncLineItemsReportV2WithHttpInfo(AsyncLineItemsReportRequest asyncLineItemsReportRequest) throws ApiException {
        okhttp3.Call localVarCall = generateAsyncLineItemsReportV2ValidateBeforeCall(asyncLineItemsReportRequest, null);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /2026-01/retail-media/reports/line-items (asynchronously)
     * Returns an asynchronous Line Items Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncLineItemsReportRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateAsyncLineItemsReportV2Async(AsyncLineItemsReportRequest asyncLineItemsReportRequest, final ApiCallback<AsyncReportResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateAsyncLineItemsReportV2ValidateBeforeCall(asyncLineItemsReportRequest, _callback);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for generateAsyncRevenueReport
     * @param asyncRevenueReportRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateAsyncRevenueReportCall(AsyncRevenueReportRequest asyncRevenueReportRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = asyncRevenueReportRequest;

        // create path and map variables
        String localVarPath = "/2026-01/retail-media/reports/revenue";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth", "oauth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateAsyncRevenueReportValidateBeforeCall(AsyncRevenueReportRequest asyncRevenueReportRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'asyncRevenueReportRequest' is set
        if (asyncRevenueReportRequest == null) {
            throw new ApiException("Missing the required parameter 'asyncRevenueReportRequest' when calling generateAsyncRevenueReport(Async)");
        }

        return generateAsyncRevenueReportCall(asyncRevenueReportRequest, _callback);

    }

    /**
     * /2026-01/retail-media/reports/revenue
     * Returns an asynchronous Revenue Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncRevenueReportRequest  (required)
     * @return AsyncReportResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public AsyncReportResponse generateAsyncRevenueReport(AsyncRevenueReportRequest asyncRevenueReportRequest) throws ApiException {
        ApiResponse<AsyncReportResponse> localVarResp = generateAsyncRevenueReportWithHttpInfo(asyncRevenueReportRequest);
        return localVarResp.getData();
    }

    /**
     * /2026-01/retail-media/reports/revenue
     * Returns an asynchronous Revenue Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncRevenueReportRequest  (required)
     * @return ApiResponse&lt;AsyncReportResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AsyncReportResponse> generateAsyncRevenueReportWithHttpInfo(AsyncRevenueReportRequest asyncRevenueReportRequest) throws ApiException {
        okhttp3.Call localVarCall = generateAsyncRevenueReportValidateBeforeCall(asyncRevenueReportRequest, null);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /2026-01/retail-media/reports/revenue (asynchronously)
     * Returns an asynchronous Revenue Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncRevenueReportRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateAsyncRevenueReportAsync(AsyncRevenueReportRequest asyncRevenueReportRequest, final ApiCallback<AsyncReportResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateAsyncRevenueReportValidateBeforeCall(asyncRevenueReportRequest, _callback);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for generateAsyncUnfilledPlacementsReport
     * @param asyncUnfilledPlacementsReportRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateAsyncUnfilledPlacementsReportCall(AsyncUnfilledPlacementsReportRequest asyncUnfilledPlacementsReportRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = asyncUnfilledPlacementsReportRequest;

        // create path and map variables
        String localVarPath = "/2026-01/retail-media/reports/unfilled-placements";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth", "oauth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateAsyncUnfilledPlacementsReportValidateBeforeCall(AsyncUnfilledPlacementsReportRequest asyncUnfilledPlacementsReportRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'asyncUnfilledPlacementsReportRequest' is set
        if (asyncUnfilledPlacementsReportRequest == null) {
            throw new ApiException("Missing the required parameter 'asyncUnfilledPlacementsReportRequest' when calling generateAsyncUnfilledPlacementsReport(Async)");
        }

        return generateAsyncUnfilledPlacementsReportCall(asyncUnfilledPlacementsReportRequest, _callback);

    }

    /**
     * /2026-01/retail-media/reports/unfilled-placements
     * Returns an asynchronous Unfilled Placements Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncUnfilledPlacementsReportRequest  (required)
     * @return AsyncReportResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public AsyncReportResponse generateAsyncUnfilledPlacementsReport(AsyncUnfilledPlacementsReportRequest asyncUnfilledPlacementsReportRequest) throws ApiException {
        ApiResponse<AsyncReportResponse> localVarResp = generateAsyncUnfilledPlacementsReportWithHttpInfo(asyncUnfilledPlacementsReportRequest);
        return localVarResp.getData();
    }

    /**
     * /2026-01/retail-media/reports/unfilled-placements
     * Returns an asynchronous Unfilled Placements Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncUnfilledPlacementsReportRequest  (required)
     * @return ApiResponse&lt;AsyncReportResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AsyncReportResponse> generateAsyncUnfilledPlacementsReportWithHttpInfo(AsyncUnfilledPlacementsReportRequest asyncUnfilledPlacementsReportRequest) throws ApiException {
        okhttp3.Call localVarCall = generateAsyncUnfilledPlacementsReportValidateBeforeCall(asyncUnfilledPlacementsReportRequest, null);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /2026-01/retail-media/reports/unfilled-placements (asynchronously)
     * Returns an asynchronous Unfilled Placements Report  &lt;br /&gt;  This endpoint is subject to specific rate limits.
     * @param asyncUnfilledPlacementsReportRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateAsyncUnfilledPlacementsReportAsync(AsyncUnfilledPlacementsReportRequest asyncUnfilledPlacementsReportRequest, final ApiCallback<AsyncReportResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateAsyncUnfilledPlacementsReportValidateBeforeCall(asyncUnfilledPlacementsReportRequest, _callback);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getAsyncExportOutput
     * @param reportId The ID of the report to retrieve (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAsyncExportOutputCall(String reportId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/2026-01/retail-media/reports/{reportId}/output"
            .replace("{" + "reportId" + "}", localVarApiClient.escapeString(reportId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth", "oauth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAsyncExportOutputValidateBeforeCall(String reportId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'reportId' is set
        if (reportId == null) {
            throw new ApiException("Missing the required parameter 'reportId' when calling getAsyncExportOutput(Async)");
        }

        return getAsyncExportOutputCall(reportId, _callback);

    }

    /**
     * /2026-01/retail-media/reports/{reportId}/output
     * Returns the output of an async report
     * @param reportId The ID of the report to retrieve (required)
     * @return File
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public File getAsyncExportOutput(String reportId) throws ApiException {
        ApiResponse<File> localVarResp = getAsyncExportOutputWithHttpInfo(reportId);
        return localVarResp.getData();
    }

    /**
     * /2026-01/retail-media/reports/{reportId}/output
     * Returns the output of an async report
     * @param reportId The ID of the report to retrieve (required)
     * @return ApiResponse&lt;File&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<File> getAsyncExportOutputWithHttpInfo(String reportId) throws ApiException {
        okhttp3.Call localVarCall = getAsyncExportOutputValidateBeforeCall(reportId, null);
        Type localVarReturnType = new TypeToken<File>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /2026-01/retail-media/reports/{reportId}/output (asynchronously)
     * Returns the output of an async report
     * @param reportId The ID of the report to retrieve (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAsyncExportOutputAsync(String reportId, final ApiCallback<File> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAsyncExportOutputValidateBeforeCall(reportId, _callback);
        Type localVarReturnType = new TypeToken<File>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getAsyncExportStatus
     * @param reportId The ID of the report to retrieve (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAsyncExportStatusCall(String reportId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/2026-01/retail-media/reports/{reportId}/status"
            .replace("{" + "reportId" + "}", localVarApiClient.escapeString(reportId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth", "oauth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAsyncExportStatusValidateBeforeCall(String reportId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'reportId' is set
        if (reportId == null) {
            throw new ApiException("Missing the required parameter 'reportId' when calling getAsyncExportStatus(Async)");
        }

        return getAsyncExportStatusCall(reportId, _callback);

    }

    /**
     * /2026-01/retail-media/reports/{reportId}/status
     * Returns the status of an async report
     * @param reportId The ID of the report to retrieve (required)
     * @return AsyncReportResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public AsyncReportResponse getAsyncExportStatus(String reportId) throws ApiException {
        ApiResponse<AsyncReportResponse> localVarResp = getAsyncExportStatusWithHttpInfo(reportId);
        return localVarResp.getData();
    }

    /**
     * /2026-01/retail-media/reports/{reportId}/status
     * Returns the status of an async report
     * @param reportId The ID of the report to retrieve (required)
     * @return ApiResponse&lt;AsyncReportResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AsyncReportResponse> getAsyncExportStatusWithHttpInfo(String reportId) throws ApiException {
        okhttp3.Call localVarCall = getAsyncExportStatusValidateBeforeCall(reportId, null);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /2026-01/retail-media/reports/{reportId}/status (asynchronously)
     * Returns the status of an async report
     * @param reportId The ID of the report to retrieve (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAsyncExportStatusAsync(String reportId, final ApiCallback<AsyncReportResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAsyncExportStatusValidateBeforeCall(reportId, _callback);
        Type localVarReturnType = new TypeToken<AsyncReportResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
