name: Generate Python Sources

on:
  push:
    paths:
      - 'api-specifications/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate Sdk
        run: |
          chmod +x ./scripts/build_python_sdk.sh
          ./scripts/build_python_sdk.sh
        shell: bash

      - name: Upload Sdk
        uses: actions/upload-artifact@v2
        with:
          name: generated-sources-python
          path: ./generated-sources/python

      - name: Push python SDK
        env:
          SDK_REPO_PRIVATE_KEY: ${{ secrets.PYTHON_SDK_REPO_PRIVATE_KEY }}
        run: |
          chmod +x ./scripts/push_sdk.sh
          ./scripts/push_sdk.sh python
        shell: bash

      - name: Send success notification plugin
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: criteo-api-sdk-generator
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Python build succeeded. <https://github.com/criteo/criteo-api-sdk-generator/actions/runs/${{github.run_id}}|Link to build>
          SLACK_USERNAME: sdk-generation-bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: ''
          SLACK_ICON_EMOJI: green_check_mark
      
      - name: Send failure notification plugin
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: criteo-api-sdk-generator
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Python build failed. <https://github.com/criteo/criteo-api-sdk-generator/actions/runs/${{github.run_id}}|Link to build>
          SLACK_USERNAME: sdk-generation-bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: ''
          SLACK_ICON_EMOJI: x
