name: Generate Python Sources

on:
  push:
    paths:
      - 'api-specifications/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate Sdk
        run: |
          chmod +x ./scripts/build_python_sdk.sh
          ./scripts/build_python_sdk.sh
        shell: bash

      - name: Upload Sdk
        uses: actions/upload-artifact@v2
        with:
          name: generated-sources-python
          path: ./generated-sources/python