name: Hello World Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Hello World Step
        run: |
          chmod +x ./scripts/build_sdk.sh
          ./scripts/build_sdk.sh
        shell: bash