name: Update OAS

on:
  workflow_dispatch:
    inputs:
        latest-version:
          type: string
          description: latest API version to onboard (ex 2026-07)
        release-candidate:
          type: boolean
          description: skip cleanup of obsolete versions (use for release candidates)
          default: false

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  update-oas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: update OAS
        run: |
          EXTRA_ARGS=""
          if [ "${{ github.event.inputs.release-candidate }}" == "true" ]; then
            EXTRA_ARGS="--no-cleanup"
          fi
          python scripts/update_specification_files.py -s api-specifications -g https://api.criteo.com -r ${{ github.event.inputs.latest-version }} $EXTRA_ARGS

      - name: Create new branch and commit files
        run: |
          git config --global user.name "update-oas-bot"
          git config --global user.email "update-oas-bot]@users.noreply.github.com"
          git checkout -b update-oas-$(date --rfc-3339=date)
          git add *
          git commit -m "Update OAS for ${{ github.event.inputs.latest-version }}${{ github.event.inputs.release-candidate == 'true' && ' (RC)' || '' }}"
          git push origin update-oas-$(date --rfc-3339=date)

      - name: Create pull request on main
        run: gh pr create --base main --head update-oas-$(date --rfc-3339=date) --title "Update OAS for ${{ github.event.inputs.latest-version }}${{ github.event.inputs.release-candidate == 'true' && ' (RC)' || '' }}" --body "Update OAS for ${{ github.event.inputs.latest-version }}${{ github.event.inputs.release-candidate == 'true' && ' (RC — no version cleanup performed)' || '' }}"
        env:
          GH_TOKEN: ${{ github.token }}
