/*
 * Criteo API
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: 2026-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.retailmedia.v2026_01.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The match type of a keyword.
 */
@JsonAdapter(MatchTypeModel.Adapter.class)
public enum MatchTypeModel {
  
  POSITIVEEXACTMATCH("PositiveExactMatch"),
  
  NEGATIVEEXACTMATCH("NegativeExactMatch"),
  
  NEGATIVEBROADMATCH("NegativeBroadMatch");

  private String value;

  MatchTypeModel(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MatchTypeModel fromValue(String value) {
    for (MatchTypeModel b : MatchTypeModel.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MatchTypeModel> {
    @Override
    public void write(final JsonWriter jsonWriter, final MatchTypeModel enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MatchTypeModel read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return MatchTypeModel.fromValue(value);
    }
  }
}

